update opcodes set version_range1=547, version_range2=838 where version_range1=0 and version_range2=0;
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LoginRequestMsg', 0);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LoginByNumRequestMsg', 1);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WSLoginRequestMsg', 2);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ESLoginRequestMsg', 3);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LoginReplyMsg', 4);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WorldListMsg', 8);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WorldStatusChangeMsg', 6);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_AllWSDescRequestMsg', 7);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WSStatusReplyMsg', 5);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_AllCharactersDescRequestMsg', 9);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_AllCharactersDescReplyMsg', 10);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CreateCharacterRequestMsg', 11);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CreateCharacterReplyMsg', 12);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WSCreateCharacterRequestMsg', 13);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WSCreateCharacterReplyMsg', 14);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DeleteCharacterRequestMsg', 15);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DeleteCharacterReplyMsg', 16);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PlayCharacterRequestMsg', 17);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PlayCharacterReplyMsg', 18);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ServerPlayCharacterRequestMsg', 19);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ServerPlayCharacterReplyMsg', 20);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ESInitMsg', 21);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ESReadyForClientsMsg', 22);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CreateZoneInstanceMsg', 23);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ZoneInstanceCreateReplyMsg', 24);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ZoneInstanceDestroyedMsg', 25);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ExpectClientAsCharacterRequestMsg', 26);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ExpectClientAsCharacterReplyMsg', 27);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ZoneInfoMsg', 28);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DoneLoadingZoneResourcesMsg', 29);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DoneSendingInitialEntitiesMsg', 30);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DoneLoadingEntityResourcesMsg', 31);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PredictionUpdateMsg', 32);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_RemoteCmdMsg', 34);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_SetRemoteCmdsMsg', 33);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_GameWorldTimeMsg', 35);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_MOTDMsg', 36);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ZoneMOTDMsg', 37);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_AvatarCreatedMsg', 38);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_AvatarDestroyedMsg', 39);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_RequestCampMsg', 40);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CampStartedMsg', 41);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CampAbortedMsg', 42);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WhoQueryRequestMsg', 43);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WhoQueryReplyMsg', 44);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_MonitorReplyMsg', 45);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_MonitorCharacterListMsg', 46);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_MonitorCharacterListRequestMsg', 47);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ClientCmdMsg', 48);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DispatchClientCmdMsg', 49);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DispatchESMsg', 50);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateTargetMsg', 51);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateOpportunityMsg', 60);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateTargetLocMsg', 52);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateCharacterSheetMsg', 53);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateSpellBookMsg', 54);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateInventoryMsg', 56);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateRecipeBookMsg', 57);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateSkillBookMsg', 58);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateSkillsMsg', 59);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChangeZoneMsg', 62);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ClientTeleportRequestMsg', 63);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_TeleportWithinZoneMsg', 64);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_TeleportWithinZoneNoReloadMsg', 65);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_MigrateClientToZoneRequestMsg', 66);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_MigrateClientToZoneReplyMsg', 67);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ReadyToZoneMsg', 68);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_AddClientToGroupMsg', 69);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_AddGroupToGroupMsg', 70);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_RemoveClientFromGroupMsg', 71);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_RemoveGroupFromGroupMsg', 72);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_MakeGroupLeaderMsg', 73);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_GroupCreatedMsg', 74);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_GroupDestroyedMsg', 75);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_GroupMemberAddedMsg', 76);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_GroupMemberRemovedMsg', 77);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_GroupRemovedFromGroupMsg', 78);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_GroupLeaderChangedMsg', 79);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_GroupSettingsChangedMsg', 80);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_SendLatestRequestMsg', 81);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ClearDataMsg', 82);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_SetSocialMsg', 83);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ESStatusMsg', 84);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ESZoneInstanceStatusMsg', 85);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ZonesStatusRequestMsg', 86);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ZonesStatusMsg', 87);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ESWeatherRequestMsg', 88);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ESWeatherRequestEndMsg', 89);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WSWeatherUpdateMsg', 90);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DialogSelectMsg', 91);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DialogCloseMsg', 92);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_RemoveSpellEffectMsg', 93);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_RemoveConcentrationMsg', 94);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_QuestJournalOpenMsg', 95);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_QuestJournalInspectMsg', 96);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_QuestJournalSetVisibleMsg', 97);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_QuestJournalWaypointMsg', 98);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CreateGuildRequestMsg', 99);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CreateGuildReplyMsg', 100);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_GuildsayMsg', 101);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_GuildKickMsg', 102);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_GuildUpdateMsg', 103);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_FellowshipExpMsg', 104);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ConsignmentUpdateMsg', 105);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ConsignItemRequestMsg', 106);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ConsignItemResponseMsg', 107);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PurchaseConsignmentRequestMsg', 108);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PurchaseConsignmentResponseMsg', 109);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ProcessScriptMsg', 110);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ProcessWorkspaceMsg', 111);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_HouseDeletedRemotelyMsg', 112);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateHouseDataMsg', 113);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateHouseAccessDataMsg', 114);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PlayerHouseBaseScreenMsg', 115);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PlayerHousePurchaseScreenMsg', 116);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PlayerHouseAccessUpdateMsg', 117);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PlayerHouseDisplayStatusMsg', 118);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PlayerHouseCloseUIMsg', 119);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_BuyPlayerHouseMsg', 120);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_BuyPlayerHouseTintMsg', 121);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CollectAllHouseItemsMsg', 122);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_RelinquishHouseMsg', 123);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EnterHouseMsg', 124);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ExitHouseMsg', 125);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ExamineConsignmentRequestMsg', 139);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EnterMoveObjectModeMsg', 130);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PositionMoveableObject', 131);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ShaderCustomizationMsg', 132);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ReplaceableSubMeshesMsg', 133);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ExamineConsignmentResponseMsg', 140);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_HouseDefaultAccessSetMsg', 126);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_HouseAccessSetMsg', 127);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_HouseAccessRemoveMsg', 128);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PayHouseUpkeepMsg', 129);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_TintWidgetsMsg', 138);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UISettingsResponseMsg', 141);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_KeymapLoadMsg', 142);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_KeymapNoneMsg', 143);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_KeymapDataMsg', 144);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_KeymapSaveMsg', 145);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DispatchSpellCmdMsg', 146);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_HouseCustomizationScreenMsg', 134);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CustomizationPurchaseRequestMsg', 135);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CustomizationSetRequestMsg', 136);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CustomizationReplyMsg', 137);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EntityVerbsRequestMsg', 148);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EntityVerbsReplyMsg', 149);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EntityVerbsVerbMsg', 150);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChatRelationshipUpdateMsg', 151);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChatFriendLoginStatusMsg', 152);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChatCreateChannelMsg', 228);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChatJoinChannelMsg', 229);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChatWhoChannelMsg', 230);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChatLeaveChannelMsg', 231);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChatTellChannelMsg', 232);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChatTellUserMsg', 233);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChatToggleFriendMsg', 234);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChatToggleIgnoreMsg', 235);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChatSendFriendsMsg', 236);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChatSendIgnoresMsg', 237);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChatFiltersMsg', 238);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LootItemsRequestMsg', 153);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_StoppedLootingMsg', 154);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_SitMsg', 155);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_StandMsg', 156);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_SatMsg', 157);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_StoodMsg', 158);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ExamineItemRequestMsg', 159);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DefaultGroupOptionsRequestMsg', 160);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DefaultGroupOptionsMsg', 161);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_GroupOptionsMsg', 162);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DisplayGroupOptionsScreenMsg', 163);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DisplayInnVisitScreenMsg', 164);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DumpSchedulerMsg', 165);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LSRequestPlayerDescMsg', 166);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LSCheckAcctLockMsg', 167);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WSAcctLockStatusMsg', 168);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_RequestHelpRepathMsg', 169);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateMotdMsg', 171);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_RequestTargetLocMsg', 170);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PerformPlayerKnockbackMsg', 172);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PerformCameraShakeMsg', 173);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PopulateSkillMapsMsg', 174);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CancelledFeignMsg', 175);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_SignalMsg', 176);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ShowCreateFromRecipeUIMsg', 177);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CancelCreateFromRecipeMsg', 178);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_BeginItemCreationMsg', 179);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_StopItemCreationMsg', 180);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ShowItemCreationProcessUIMsg', 181);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateItemCreationProcessUIMsg', 182);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DisplayTSEventReactionMsg', 183);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ShowRecipeBookMsg', 184);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_KnowledgebaseRequestMsg', 185);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_KnowledgebaseResponseMsg', 186);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CSTicketHeaderRequestMsg', 187);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CSTicketInfoMsg', 188);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CSTicketCommentRequestMsg', 189);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CSTicketCommentResponseMsg', 190);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CSTicketCreateMsg', 191);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CSTicketAddCommentMsg', 192);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CSTicketDeleteMsg', 193);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CSTicketChangeNotificationMsg', 194);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WorldDataUpdateMsg', 195);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_KnownLanguagesMsg', 196);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LsRequestClientCrashLogMsg', 197);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LsClientBaselogReplyMsg', 198);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LsClientCrashlogReplyMsg', 199);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LsClientAlertlogReplyMsg', 200);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LsClientVerifylogReplyMsg', 201);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ClientTeleportToLocationMsg', 202);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateClientPredFlagsMsg', 203);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ChangeServerControlFlagMsg', 204);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CSToolsRequestMsg', 205);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CSToolsResponseMsg', 206);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_AddSocialStructureStandingMsg', 207);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CreateBoatTransportsMsg', 208);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_PositionBoatTransportMsg', 209);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_MigrateBoatTransportMsg', 210);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_MigrateBoatTransportReplyMsg', 211);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_DisplayDebugNLLPointsMsg', 212);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ExamineInfoRequestMsg', 213);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_QuickbarInitMsg', 214);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_QuickbarUpdateMsg', 215);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_MacroInitMsg', 216);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_MacroUpdateMsg', 217);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_QuestionnaireMsg', 218);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LevelChangedMsg', 219);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_SpellGainedMsg', 220);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EncounterBrokenMsg', 221);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_OnscreenMsgMsg', 222);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ModifyGuildMsg', 223);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_RewardPackMsg', 224);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_RenameGuildMsg', 225);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ZoneToFriendRequestMsg', 226);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ZoneToFriendReplyMsg', 227);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WaypointRequestMsg', 239);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WaypointReplyMsg', 240);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WaypointSelectMsg', 241);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WaypointUpdateMsg', 242);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CharNameChangedMsg', 243);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ShowZoneTeleporterDestinationsMsg', 244);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_SelectZoneTeleporterDestinationMsg', 245);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ReloadLocalizedTxtMsg', 246);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_RequestGuildMembershipMsg', 247);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_GuildMembershipResponseMsg', 248);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LeaveGuildNotifyMsg', 249);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_JoinGuildNotifyMsg', 250);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_AvatarUpdateMsg', 251);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_BioUpdateMsg', 252);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_InspectPlayerMsg', 253);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_WSServerLockMsg', 254);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LSServerLockMsg', 255);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CsCategoryRequestMsg', 256);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_CsCategoryResponseMsg', 257);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_KnowledgeWindowSlotMappingMsg', 258);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_LFGUpdateMsg', 259);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_AFKUpdateMsg', 260);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateActivePublicZonesMsg', 261);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UnknownNpcMsg', 262);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ConsumableItemsDetailsMsg', 263);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ConsignViewCreateMsg', 264);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ConsignViewGetPageMsg', 265);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ConsignViewReleaseMsg', 266);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateDebugRadiiMsg', 268);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ConsignRemoveItemsMsg', 267);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_SnoopMsg', 269);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ReportMsg', 270);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_UpdateRaidMsg', 271);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_ConsignViewSortMsg', 272);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqHearChatCmd', 273);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqDisplayTextCmd', 274);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqCreateGhostCmd', 275);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqCreateWidgetCmd', 276);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqCreateSignWidgetCmd', 277);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqUpdateSignWidgetCmd', 332);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqDestroyGhostCmd', 278);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqUpdateGhostCmd', 279);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqSetControlGhostCmd', 280);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqSetPOVGhostCmd', 281);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqHearCombatCmd', 282);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqHearSpellCastCmd', 283);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqHearSpellInterruptCmd', 284);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqHearSpellFizzleCmd', 285);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqHearConsiderCmd', 286);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqUpdateSubClassesCmd', 287);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqCreateListBoxCmd', 288);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqSetDebugPathPointsCmd', 289);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqCannedEmoteCmd', 290);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqStateCmd', 291);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqPlaySoundCmd', 292);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqPlaySound3DCmd', 293);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqPlayVoiceCmd', 294);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqHearDrowningCmd', 295);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqHearDeathCmd', 296);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqGroupMemberRemovedCmd', 297);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqHearChainEffectCmd', 298);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqReceiveOfferCmd', 299);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqInspectPCResultsCmd', 300);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqDrawablePathGraphCmd', 301);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqDialogOpenCmd', 302);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqDialogCloseCmd', 303);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqQuestJournalUpdateCmd', 304);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqQuestGroupCmd', 306);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqQuestJournalReplyCmd', 305);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqStartBrokerCmd', 343);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqUpdateMerchantCmd', 307);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqUpdateStoreCmd', 308);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqUpdatePlayerTradeCmd', 309);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqHelpPathCmd', 310);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqHelpPathClearCmd', 311);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqUpdateBankCmd', 312);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqExamineInfoCmd', 313);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqUpdateLootCmd', 314);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqJunctionListCmd', 315);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqShowDeathWindowCmd', 316);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqDisplaySpellFailCmd', 317);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqSpellCastStartCmd', 318);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqSpellCastEndCmd', 319);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqResurrectedCmd', 320);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqChoiceWinCmd', 321);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqSetDefaultVerbCmd', 322);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqInstructionWindowCmd', 323);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqInstructionWindowCloseCmd', 324);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqInstructionWindowGoalCmd', 325);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqInstructionWindowTaskCmd', 326);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqEnableGameEventCmd', 327);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqShowWindowCmd', 328);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqEnableWindowCmd', 329);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqFlashWindowCmd', 330);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqHearPlayFlavorCmd', 331);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqDebugPVDCmd', 333);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqShowBookCmd', 334);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqQuestionnaireCmd', 335);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqGetProbsCmd', 336);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqHearHealCmd', 337);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqChatChannelUpdateCmd', 338);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqWhoChannelQueryReplyCmd', 339);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqAvailWorldChannelsCmd', 340);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqUpdateTargetCmd', 341);
insert into opcodes (version_range1, version_range2, name, opcode) values(0, 283, 'OP_EqConsignmentItemsCmd', 342);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LoginRequestMsg', 0);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LoginByNumRequestMsg', 1);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WSLoginRequestMsg', 2);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ESLoginRequestMsg', 3);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LoginReplyMsg', 4);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WSStatusReplyMsg', 5);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WorldStatusChangeMsg', 6);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AllWSDescRequestMsg', 7);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WorldListMsg', 8);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AllCharactersDescRequestMsg', 9);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AllCharactersDescReplyMsg', 10);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CreateCharacterRequestMsg', 11);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CreateCharacterReplyMsg', 12);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WSCreateCharacterRequestMsg', 13);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WSCreateCharacterReplyMsg', 14);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ReskinCharacterRequestMsg', 15);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DeleteCharacterRequestMsg', 16);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DeleteCharacterReplyMsg', 17);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PlayCharacterRequestMsg', 18);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PlayCharacterReplyMsg', 19);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ServerPlayCharacterRequestMsg', 20);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ServerPlayCharacterReplyMsg', 21);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ESInitMsg', 22);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ESReadyForClientsMsg', 23);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CreateZoneInstanceMsg', 24);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ZoneInstanceCreateReplyMsg', 25);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ZoneInstanceDestroyedMsg', 26);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ExpectClientAsCharacterRequest', 27);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ExpectClientAsCharacterReplyMs', 28);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ZoneInfoMsg', 29);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DoneLoadingZoneResourcesMsg', 30);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DoneSendingInitialEntitiesMsg', 31);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DoneLoadingEntityResourcesMsg', 32);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DoneLoadingUIResourcesMsg', 33);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PredictionUpdateMsg', 34);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_SetRemoteCmdsMsg', 35);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RemoteCmdMsg', 36);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GameWorldTimeMsg', 37);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MOTDMsg', 38);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ZoneMOTDMsg', 39);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AvatarCreatedMsg', 40);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AvatarDestroyedMsg', 41);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RequestCampMsg', 42);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CampStartedMsg', 43);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CampAbortedMsg', 44);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WhoQueryRequestMsg', 45);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WhoQueryReplyMsg', 46);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MonitorReplyMsg', 47);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MonitorCharacterListMsg', 48);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MonitorCharacterListRequestMsg', 49);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ClientCmdMsg', 50);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DispatchClientCmdMsg', 51);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DispatchESMsg', 52);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateTargetMsg', 53);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateTargetLocMsg', 54);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateCharacterSheetMsg', 55);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateSpellBookMsg', 56);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateInventoryMsg', 58);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateRecipeBookMsg', 60);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RequestRecipeDetailsMsg', 61);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RecipeDetailsMsg', 62);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateSkillBookMsg', 63);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateSkillsMsg', 64);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateOpportunityMsg', 65);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ChangeZoneMsg', 66);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ClientTeleportRequestMsg', 68);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_TeleportWithinZoneMsg', 69);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_TeleportWithinZoneNoReloadMsg', 70);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MigrateClientToZoneRequestMsg', 71);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MigrateClientToZoneReplyMsg', 72);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ReadyToZoneMsg', 73);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AddClientToGroupMsg', 74);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AddGroupToGroupMsg', 75);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RemoveClientFromGroupMsg', 76);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RemoveGroupFromGroupMsg', 77);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MakeGroupLeaderMsg', 78);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GroupCreatedMsg', 79);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GroupDestroyedMsg', 80);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GroupMemberAddedMsg', 81);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GroupMemberRemovedMsg', 82);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GroupRemovedFromGroupMsg', 83);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GroupLeaderChangedMsg', 84);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GroupResendOOZDataMsg', 85);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GroupSettingsChangedMsg', 86);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_SendLatestRequestMsg', 88);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ClearDataMsg', 89);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_SetSocialMsg', 90);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ESStatusMsg', 91);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ESZoneInstanceStatusMsg', 92);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ZonesStatusRequestMsg', 93);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ZonesStatusMsg', 94);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ESWeatherRequestMsg', 95);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ESWeatherRequestEndMsg', 96);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WSWeatherUpdateMsg', 97);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DialogSelectMsg', 98);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DialogCloseMsg', 99);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RemoveSpellEffectMsg', 100);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RemoveConcentrationMsg', 101);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_QuestJournalOpenMsg', 102);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_QuestJournalInspectMsg', 103);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_QuestJournalSetVisibleMsg', 104);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_QuestJournalWaypointMsg', 105);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CreateGuildRequestMsg', 106);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CreateGuildReplyMsg', 107);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildsayMsg', 108);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildKickMsg', 109);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildUpdateMsg', 110);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DeleteGuildMsg', 111);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_FellowshipExpMsg', 112);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ConsignmentCloseStoreMsg', 113);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ConsignItemRequestMsg', 114);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ConsignItemResponseMsg', 115);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PurchaseConsignmentRequestMsg', 116);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PurchaseConsignmentResponseMsg', 117);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ProcessScriptMsg', 118);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ProcessWorkspaceMsg', 119);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_HouseDeletedRemotelyMsg', 120);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateHouseDataMsg', 121);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateHouseAccessDataMsg', 122);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PlayerHouseBaseScreenMsg', 123);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PlayerHousePurchaseScreenMsg', 124);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PlayerHouseAccessUpdateMsg', 125);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PlayerHouseDisplayStatusMsg', 126);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PlayerHouseCloseUIMsg', 127);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_BuyPlayerHouseMsg', 128);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_BuyPlayerHouseTintMsg', 129);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CollectAllHouseItemsMsg', 130);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RelinquishHouseMsg', 131);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EnterHouseMsg', 132);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ExitHouseMsg', 133);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_HouseDefaultAccessSetMsg', 134);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_HouseAccessSetMsg', 135);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_HouseAccessRemoveMsg', 136);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PayHouseUpkeepMsg', 137);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MoveableObjectPlacementCriteri', 138);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EnterMoveObjectModeMsg', 139);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PositionMoveableObject', 140);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CancelMoveObjectModeMsg', 141);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ShaderCustomizationMsg', 142);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ReplaceableSubMeshesMsg', 143);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_HouseCustomizationScreenMsg', 144);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CustomizationPurchaseRequestMs', 145);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CustomizationSetRequestMsg', 146);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CustomizationReplyMsg', 147);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_TintWidgetsMsg', 148);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ExamineConsignmentRequestMsg', 149);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ExamineConsignmentResponseMsg', 150);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UISettingsResponseMsg', 151);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UIResetMsg', 152);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_KeymapLoadMsg', 153);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_KeymapNoneMsg', 154);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_KeymapDataMsg', 155);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_KeymapSaveMsg', 156);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DispatchSpellCmdMsg', 157);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EntityVerbsRequestMsg', 159);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EntityVerbsReplyMsg', 160);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EntityVerbsVerbMsg', 161);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ChatRelationshipUpdateMsg', 162);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LootItemsRequestMsg', 163);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_StoppedLootingMsg', 164);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_SitMsg', 165);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_StandMsg', 166);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_SatMsg', 167);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_StoodMsg', 168);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ClearForTakeOffMsg', 169);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ReadyForTakeOffMsg', 170);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ShowIllusionsMsg', 171);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_HideIllusionsMsg', 172);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ExamineItemRequestMsg', 173);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ReadBookPageMsg', 174);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DefaultGroupOptionsRequestMsg', 175);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DefaultGroupOptionsMsg', 176);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GroupOptionsMsg', 177);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DisplayGroupOptionsScreenMsg', 178);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DisplayInnVisitScreenMsg', 179);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DumpSchedulerMsg', 180);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LSRequestPlayerDescMsg', 181);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LSCheckAcctLockMsg', 182);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WSAcctLockStatusMsg', 183);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RequestHelpRepathMsg', 184);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RequestTargetLocMsg', 185);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateMotdMsg', 186);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PerformPlayerKnockbackMsg', 187);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PerformCameraShakeMsg', 188);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PopulateSkillMapsMsg', 189);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CancelledFeignMsg', 190);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_SignalMsg', 191);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ShowCreateFromRecipeUIMsg', 192);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CancelCreateFromRecipeMsg', 193);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_BeginItemCreationMsg', 194);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_StopItemCreationMsg', 195);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ShowItemCreationProcessUIMsg', 196);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateItemCreationProcessUIMsg', 197);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DisplayTSEventReactionMsg', 198);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ShowRecipeBookMsg', 199);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_KnowledgebaseRequestMsg', 200);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_KnowledgebaseResponseMsg', 201);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CSTicketHeaderRequestMsg', 202);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CSTicketInfoMsg', 203);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CSTicketCommentRequestMsg', 204);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CSTicketCommentResponseMsg', 205);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CSTicketCreateMsg', 206);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CSTicketAddCommentMsg', 207);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CSTicketDeleteMsg', 208);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CSTicketChangeNotificationMsg', 209);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WorldDataUpdateMsg', 210);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_KnownLanguagesMsg', 211);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LsRequestClientCrashLogMsg', 212);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LsClientBaselogReplyMsg', 213);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LsClientCrashlogReplyMsg', 214);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LsClientDetailedCrashlogReplyMsg', 215);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LsClientAlertlogReplyMsg', 216);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LsClientVerifylogReplyMsg', 217);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ClientTeleportToLocationMsg', 218);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateClientPredFlagsMsg', 219);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ChangeServerControlFlagMsg', 220);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CSToolsRequestMsg', 221);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CSToolsResponseMsg', 222);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AddSocialStructureStandingMsg', 223);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CreateBoatTransportsMsg', 224);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PositionBoatTransportMsg', 225);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MigrateBoatTransportMsg', 226);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MigrateBoatTransportReplyMsg', 227);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DisplayDebugNLLPointsMsg', 228);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ExamineInfoRequestMsg', 229);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_QuickbarInitMsg', 230);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_QuickbarUpdateMsg', 231);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MacroInitMsg', 232);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MacroUpdateMsg', 233);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_QuestionnaireMsg', 234);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LevelChangedMsg', 235);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_SpellGainedMsg', 236);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EncounterBrokenMsg', 237);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_OnscreenMsgMsg', 238);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DisplayWarningMsg', 239);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ModifyGuildMsg', 240);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildEventMsg', 241);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildEventAddMsg', 242);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildEventActionMsg', 243);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildEventListMsg', 244);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RequestGuildEventDetailsMsg', 245);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildEventDetailsMsg', 246);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RequestGuildInfoMsg', 247);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildBankActionMsg', 248);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildBankActionResponseMsg', 249);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildBankItemDetailsRequestMsg', 250);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildBankItemDetailsResponseMs', 251);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildBankUpdateMsg', 252);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildBankEventListMsg', 253);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RequestGuildBankEventDetailsMs', 254);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RewardPackMsg', 255);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RenameGuildMsg', 256);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ZoneToFriendRequestMsg', 257);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ZoneToFriendReplyMsg', 258);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ChatCreateChannelMsg', 259);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ChatJoinChannelMsg', 260);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ChatWhoChannelMsg', 261);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ChatLeaveChannelMsg', 262);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ChatTellChannelMsg', 263);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ChatTellUserMsg', 264);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ChatToggleFriendMsg', 265);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ChatToggleIgnoreMsg', 266);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ChatSendFriendsMsg', 267);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ChatSendIgnoresMsg', 268);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ChatFiltersMsg', 269);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MailGetHeadersMsg', 270);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MailGetMessageMsg', 271);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MailSendMessageMsg', 272);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MailDeleteMessageMsg', 273);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MailGetHeadersReplyMsg', 274);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MailGetMessageReplyMsg', 275);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MailSendMessageReplyMsg', 276);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MailCommitSendMessageMsg', 277);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MailSendSystemMessageMsg', 278);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MailRemoveAttachFromMailMsg', 279);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WaypointRequestMsg', 280);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WaypointReplyMsg', 281);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WaypointSelectMsg', 282);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WaypointUpdateMsg', 283);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CharNameChangedMsg', 284);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ShowZoneTeleporterDestinations', 285);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_SelectZoneTeleporterDestinatio', 286);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ReloadLocalizedTxtMsg', 287);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RequestGuildMembershipMsg', 288);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GuildMembershipResponseMsg', 289);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LeaveGuildNotifyMsg', 290);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_JoinGuildNotifyMsg', 291);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AvatarUpdateMsg', 292);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_BioUpdateMsg', 293);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_InspectPlayerMsg', 294);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WSServerLockMsg', 295);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LSServerLockMsg', 296);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WSServerHideMsg', 297);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CsCategoryRequestMsg', 298);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CsCategoryResponseMsg', 299);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_KnowledgeWindowSlotMappingMsg', 300);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_LFGUpdateMsg', 301);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AFKUpdateMsg', 302);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AnonUpdateMsg', 303);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateActivePublicZonesMsg', 304);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UnknownNpcMsg', 305);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PromoFlagsDetailsMsg', 306);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ConsignViewCreateMsg', 307);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ConsignViewGetPageMsg', 308);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ConsignViewReleaseMsg', 309);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ConsignRemoveItemsMsg', 310);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateDebugRadiiMsg', 311);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_SnoopMsg', 312);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ReportMsg', 313);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateRaidMsg', 314);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ConsignViewSortMsg', 316);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_TitleUpdateMsg', 317);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ClientFellMsg', 318);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ClientInDeathRegionMsg', 319);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CampClientMsg', 320);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CSToolAccessResponseMsg', 321);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GetAvatarAccessRequestForCSToo', 322);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_TrackingUpdateMsg', 323);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_BeginTrackingMsg', 324);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_StopTrackingMsg', 325);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AdvancementRequestMsg', 326);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateAvgFrameTimeMsg', 327);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MapFogDataInitMsg', 328);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MapFogDataUpdateMsg', 329);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CloseGroupInviteWindowMsg', 330);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_UpdateGroupMemberDataMsg', 331);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WorldPingMsg', 332);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MoveLogUpdateMsg', 333);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_OfferQuestMsg', 334);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WorldShutdownUpdateMsg', 335);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DisplayMailScreenMsg', 336);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ClientIdleBeginMsg', 337);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ClientIdleEndMsg', 338);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PurchaseConsignmentLoreCheckRe', 339);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_NotifyApprenticeStoppedMentori', 340);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CorruptedClientMsg', 341);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_WorldDataChangeMsg', 342);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_MailEventNotificationMsg', 343);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RestartZoneMsg', 344);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_FlightPathsMsg', 345);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CharacterLinkdeadMsg', 346);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CharTransferStartRequestMsg', 347);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CharTransferStartReplyMsg', 348);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CharTransferRequestMsg', 349);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CharTransferReplyMsg', 350);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CharTransferRollbackRequestMsg', 351);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CharTransferCommitRequestMsg', 352);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CharTransferRollbackReplyMsg', 353);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CharTransferCommitReplyMsg', 354);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GetCharacterSerializedRequestM', 355);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GetCharacterSerializedReplyMsg', 356);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CreateCharFromCBBRequestMsg', 357);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CreateCharFromCBBReplyMsg', 358);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_HousingDataChangedMsg', 359);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_HousingRestoreMsg', 360);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AuctionItem', 361);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AuctionItemReply', 362);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AuctionCoin', 363);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AuctionCoinReply', 364);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AuctionCharacter', 365);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AuctionCharacterReply', 366);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AuctionCommitMsg', 367);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AuctionAbortMsg', 368);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CharTransferValidateRequestMsg', 369);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_CharTransferValidateReplyMsg', 370);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_RaceRestrictionMsg', 371);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_SetInstanceDisplayNameMsg', 372);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GetAuctionAssetIDMsg', 373);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_GetAuctionAssetIDReplyMsg', 374);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_ResendWorldChannelsMsg', 375);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DisplayExchangeScreenMsg', 376);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_AuditAuctionEventMsg', 377);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_InviteRequestMsg', 401);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_InviteResponseMsg', 402);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_InviteTargetResponseMsg', 403);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_InspectPlayerRequestMsg', 404);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DispatchMsg', 405);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_DisplayEventMsg', 406);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PrePossessionMsg', 407);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_PostPossessionMsg', 408);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqHearChatCmd', 411);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqDisplayTextCmd', 412);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqCreateGhostCmd', 413);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqCreateWidgetCmd', 414);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqCreateSignWidgetCmd', 415);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqDestroyGhostCmd', 416);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqUpdateGhostCmd', 417);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqSetControlGhostCmd', 418);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqSetPOVGhostCmd', 419);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqHearCombatCmd', 420);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqHearSpellCastCmd', 421);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqHearSpellInterruptCmd', 422);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqHearSpellFizzleCmd', 423);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqHearConsiderCmd', 424);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqUpdateSubClassesCmd', 425);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqCreateListBoxCmd', 426);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqSetDebugPathPointsCmd', 428);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqCannedEmoteCmd', 429);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqStateCmd', 430);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqPlaySoundCmd', 431);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqPlaySound3DCmd', 432);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqPlayVoiceCmd', 433);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqHearDrowningCmd', 434);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqHearDeathCmd', 435);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqGroupMemberRemovedCmd', 436);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqHearChainEffectCmd', 437);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqReceiveOfferCmd', 438);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqInspectPCResultsCmd', 439);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqDrawablePathGraphCmd', 440);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqDialogOpenCmd', 441);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqDialogCloseCmd', 442);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqFactionUpdateCmd', 443);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqCollectionUpdateCmd', 444);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqCollectionFilterCmd', 445);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqCollectionItemCmd', 446);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqQuestJournalUpdateCmd', 447);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqQuestJournalReplyCmd', 448);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqQuestGroupCmd', 449);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqUpdateMerchantCmd', 450);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqUpdateStoreCmd', 451);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqUpdatePlayerTradeCmd', 452);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqHelpPathCmd', 453);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqHelpPathClearCmd', 454);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqUpdateBankCmd', 455);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqExamineInfoCmd', 456);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqUpdateLootCmd', 457);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqJunctionListCmd', 458);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqShowDeathWindowCmd', 459);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqDisplaySpellFailCmd', 460);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqSpellCastStartCmd', 461);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqSpellCastEndCmd', 462);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqResurrectedCmd', 463);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqChoiceWinCmd', 464);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqSetDefaultVerbCmd', 465);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqInstructionWindowCmd', 466);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqInstructionWindowCloseCmd', 467);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqInstructionWindowGoalCmd', 468);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqInstructionWindowTaskCmd', 469);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqEnableGameEventCmd', 470);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqShowWindowCmd', 471);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqEnableWindowCmd', 472);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqFlashWindowCmd', 473);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqHearPlayFlavorCmd', 474);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqUpdateSignWidgetCmd', 475);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqDebugPVDCmd', 476);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqShowBookCmd', 477);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqQuestionnaireCmd', 478);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqGetProbsCmd', 479);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqHearHealCmd', 480);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqChatChannelUpdateCmd', 481);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqWhoChannelQueryReplyCmd', 482);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqAvailWorldChannelsCmd', 483);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqUpdateTargetCmd', 484);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqConsignmentItemsCmd', 485);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqStartBrokerCmd', 486);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqMapExplorationCmd', 487);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqStoreLogCmd', 488);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqSpellMoveToRangeAndRetryCmd', 489);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqUpdatePlayerMailCmd', 490);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqArenaResultsCmd', 491);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqGuildBankEventActionCmd', 492);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqGuildBankExamineInfoCmd', 493);
INSERT INTO `opcodes` (`version_range1`, `version_range2`, `name`, `opcode`) VALUES (284, 546, 'OP_EqHearSpellNoLandCmd', 494);
