alter table character_details modify column xp_debt float not null default 0.0;
CREATE TABLE `character_spirit_shards` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `timestamp` BIGINT signed NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` varchar(64) not null default '',
  `level` int(10) unsigned NOT NULL DEFAULT 0,
  `race` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `gender` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `adventure_class` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `model_type` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `soga_model_type` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `hair_type` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `hair_face_type` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `wing_type` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `chest_type` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `legs_type` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `soga_hair_type` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `soga_hair_face_type` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `hide_hood` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `size` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `collision_radius` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `action_state` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `visual_state` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `mood_state` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `emote_state` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `pos_state` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `activity_status` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `sub_title` varchar(255) not null default '',
  `prefix_title` varchar(128) not null default '',
  `suffix_title` varchar(128) not null default '',
  `lastname` varchar(64) not null default '',
  `x` float not null default 0.0,
  `y` float not null default 0.0,
  `z` float not null default 0.0,
  `heading` float not null default 0.0,
  `gridid` int(10) unsigned NOT NULL DEFAULT 0,
  `zoneid` int(10) unsigned NOT NULL DEFAULT 0,
  `instanceid` int(10) unsigned NOT NULL DEFAULT 0,
  `charid` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
