--[[
    Script Name    : SpawnScripts/qeynos_combined02/aQeynoscitizen.lua
    Script Author  : Rylec
    Script Date    : 2021.03.14 08:03:20
    Script Purpose : 
                   : 
--]]

function spawn(NPC)
    local model = MakeRandomInt(3,4)

        if model == 1 then
            SetModelType(NPC, "111") -- barbarian female
            SpawnSet(NPC, "soga_model_type", "111")
            SpawnSet(NPC, "chest_type", "5457")
            SpawnSet(NPC, "legs_type", "5458")
            BarbarianCosmetics(NPC)
        elseif model == 2 then
            SetModelType(NPC, "112") -- barbarian male
            SpawnSet(NPC, "soga_model_type", "112")
            SpawnSet(NPC, "chest_type", "5461")
            SpawnSet(NPC, "legs_type", "5462")
            BarbarianCosmetics(NPC)
        elseif model == 3 then
            SetModelType(NPC, "109") -- dwarf female
            SpawnSet(NPC, "soga_model_type", "109")
            SpawnSet(NPC, "chest_type", "5473")
            SpawnSet(NPC, "legs_type", "5474")
            DwarfCosmetics(NPC)
        elseif model == 4 then
            SetModelType(NPC, "110") -- dwarf male
            SpawnSet(NPC, "soga_model_type", "110")
            SpawnSet(NPC, "chest_type", "5477")
            SpawnSet(NPC, "legs_type", "5478")
            DwarfCosmetics(NPC)
        elseif model == 5 then
            SetModelType(NPC, "121") -- gnome male
            SpawnSet(NPC, "soga_model_type", "121")
            SpawnSet(NPC, "chest_type", "5501")
            SpawnSet(NPC, "legs_type", "5502")
            GnomeCosmetics(NPC)
        else
            SetModelType(NPC, "122") -- gnome female
            SpawnSet(NPC, "soga_model_type", "122")
            SpawnSet(NPC, "chest_type", "5497")
            SpawnSet(NPC, "legs_type", "5498")
            GnomeCosmetics(NPC)
        end
end

function hailed(NPC, Spawn)
	FaceTarget(NPC, Spawn)
end

function respawn(NPC)
	spawn(NPC)
end

function BarbarianCosmetics(NPC)
    local Type = GetModelType(NPC)
    local hair = 0
    
    if Type == 111 then
        hair = MakeRandomInt(1136,1140) -- 1125, 1127, 1128, 1133
        SpawnSet(NPC, "hair_type", hair)
        SpawnSet(NPC, "soga_hair_type", hair)
    else
        hair = MakeRandomInt(1133,1140) -- 1126, 1133, 1135, 1136 
        SpawnSet(NPC, "hair_type", hair)
        SpawnSet(NPC, "soga_hair_type", hair)
    end
        
    local beard = MakeRandomInt(1185,1189) -- 1184, 1185, 1186, 1188, 1189
    local beard_chance = MakeRandomInt(1,100)    

        if beard_chance < 11 then
            SpawnSet(NPC, "facial_hair_type", "0")
            SpawnSet(NPC, "soga_facial_hair_type", "0")
        else
            SpawnSet(NPC, "facial_hair_type", beard)
            SpawnSet(NPC, "soga_facial_hair_type", beard)
        end
        
    local overall_look = MakeRandomInt(14,14)

        if overall_look == 1 then -- Brown golden highlights
            SpawnSet(NPC, "skin_color", "165 111 103")
            SpawnSet(NPC, "soga_skin_color", "165 111 103") 
            SpawnSet(NPC, "eye_color", "49 101 117")
            SpawnSet(NPC, "soga_eye_color", "49 101 117") 
            SpawnSet(NPC, "hair_type_color", "40 19 9")
            SpawnSet(NPC, "soga_hair_type_color", "40 19 9") 
            SpawnSet(NPC, "hair_face_color", "40 19 9")
            SpawnSet(NPC, "soga_hair_face_color", "40 19 9")
            SpawnSet(NPC, "hair_type_highlight_color", "119 147 147")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "119 147 147")
            SpawnSet(NPC, "hair_face_highlight_color", "119 147 147")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "119 147 147")
            SpawnSet(NPC, "hair_color1", "79 28 15")
            SpawnSet(NPC, "soga_hair_color1", "79 28 15") 
            SpawnSet(NPC, "hair_color2", "111 64 0")
            SpawnSet(NPC, "soga_hair_color2", "111 64 0") 
            SpawnSet(NPC, "hair_highlight", "114 112 142")
            SpawnSet(NPC, "soga_hair_highlight", "114 112 142") 
        elseif overall_look == 2 then -- Yellow bright
            SpawnSet(NPC, "skin_color", "121 94 57")
            SpawnSet(NPC, "soga_skin_color", "121 94 57") 
            SpawnSet(NPC, "eye_color", "136 184 199")
            SpawnSet(NPC, "soga_eye_color", "136 184 199") 
            SpawnSet(NPC, "hair_type_color", "225 181 22")
            SpawnSet(NPC, "soga_hair_type_color", "225 181 22") 
            SpawnSet(NPC, "hair_face_color", "225 181 22")
            SpawnSet(NPC, "soga_hair_face_color", "225 181 22")
            SpawnSet(NPC, "hair_type_highlight_color", "184 128 10")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "184 128 10")
            SpawnSet(NPC, "hair_face_highlight_color", "184 128 10")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "184 128 10")
            SpawnSet(NPC, "hair_color1", "239 221 86")
            SpawnSet(NPC, "soga_hair_color1", "239 221 86") 
            SpawnSet(NPC, "hair_color2", "99 53 22")
            SpawnSet(NPC, "soga_hair_color2", "99 53 22") 
            SpawnSet(NPC, "hair_highlight", "209 131 22")
            SpawnSet(NPC, "soga_hair_highlight", "209 131 22") 
        elseif overall_look == 3 then -- Chestnut
            SpawnSet(NPC, "skin_color", "255 255 255")
            SpawnSet(NPC, "soga_skin_color", "255 255 255") 
            SpawnSet(NPC, "eye_color", "102 154 140")
            SpawnSet(NPC, "soga_eye_color", "102 154 140") 
            SpawnSet(NPC, "hair_type_color", "0 0 0")
            SpawnSet(NPC, "soga_hair_type_color", "0 0 0") 
            SpawnSet(NPC, "hair_face_color", "0 0 0")
            SpawnSet(NPC, "soga_hair_face_color", "0 0 0")
            SpawnSet(NPC, "hair_type_highlight_color", "15 1 21")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "15 1 21")
            SpawnSet(NPC, "hair_face_highlight_color", "15 1 21")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "15 1 21")
            SpawnSet(NPC, "hair_color1", "38 22 21")
            SpawnSet(NPC, "soga_hair_color1", "38 22 21") 
            SpawnSet(NPC, "hair_color2", "120 50 0")
            SpawnSet(NPC, "soga_hair_color2", "120 50 0") 
            SpawnSet(NPC, "hair_highlight", "29 21 28")
            SpawnSet(NPC, "soga_hair_highlight", "29 21 28") 
        elseif overall_look == 4 then -- Yellow bright
            SpawnSet(NPC, "skin_color", "121 94 57")
            SpawnSet(NPC, "soga_skin_color", "121 94 57") 
            SpawnSet(NPC, "eye_color", "61 104 65")
            SpawnSet(NPC, "soga_eye_color", "61 104 65") 
            SpawnSet(NPC, "hair_type_color", "233 184 31")
            SpawnSet(NPC, "soga_hair_type_color", "233 184 31") 
            SpawnSet(NPC, "hair_face_color", "233 184 31")
            SpawnSet(NPC, "soga_hair_face_color", "233 184 31")
            SpawnSet(NPC, "hair_type_highlight_color", "19 6 25")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "19 6 25")
            SpawnSet(NPC, "hair_face_highlight_color", "19 6 25")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "19 6 25")
            SpawnSet(NPC, "hair_color1", "246 219 114")
            SpawnSet(NPC, "soga_hair_color1", "246 219 114") 
            SpawnSet(NPC, "hair_color2", "187 136 62")
            SpawnSet(NPC, "soga_hair_color2", "187 136 62") 
            SpawnSet(NPC, "hair_highlight", "29 21 28")
            SpawnSet(NPC, "soga_hair_highlight", "29 21 28") 
        elseif overall_look == 5 then -- White grey shine
            SpawnSet(NPC, "skin_color", "229 215 216")
            SpawnSet(NPC, "soga_skin_color", "229 215 216") 
            SpawnSet(NPC, "eye_color", "47 95 110")
            SpawnSet(NPC, "soga_eye_color", "47 95 110") 
            SpawnSet(NPC, "hair_type_color", "119 147 147")
            SpawnSet(NPC, "soga_hair_type_color", "119 147 147") 
            SpawnSet(NPC, "hair_face_color", "119 147 147")
            SpawnSet(NPC, "soga_hair_face_color", "119 147 147")
            SpawnSet(NPC, "hair_type_highlight_color", "193 100 45")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "193 100 45")
            SpawnSet(NPC, "hair_face_highlight_color", "193 100 45")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "193 100 45")
            SpawnSet(NPC, "hair_color1", "114 112 142")
            SpawnSet(NPC, "soga_hair_color1", "114 112 142") 
            SpawnSet(NPC, "hair_color2", "152 138 129")
            SpawnSet(NPC, "soga_hair_color2", "152 138 129") 
            SpawnSet(NPC, "hair_highlight", "105 26 26")
            SpawnSet(NPC, "soga_hair_highlight", "105 26 26") 
        elseif overall_look == 6 then -- Brown golden highlights
            SpawnSet(NPC, "skin_color", "229 215 216")
            SpawnSet(NPC, "soga_skin_color", "229 215 216") 
            SpawnSet(NPC, "eye_color", "105 85 44")
            SpawnSet(NPC, "soga_eye_color", "105 85 44") 
            SpawnSet(NPC, "hair_type_color", "37 22 5")
            SpawnSet(NPC, "soga_hair_type_color", "37 22 5") 
            SpawnSet(NPC, "hair_face_color", "37 22 5")
            SpawnSet(NPC, "soga_hair_face_color", "37 22 5")
            SpawnSet(NPC, "hair_type_highlight_color", "27 15 35")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "27 15 35")
            SpawnSet(NPC, "hair_face_highlight_color", "27 15 35")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "27 15 35")
            SpawnSet(NPC, "hair_color1", "79 28 15")
            SpawnSet(NPC, "soga_hair_color1", "79 28 15") 
            SpawnSet(NPC, "hair_color2", "111 64 0")
            SpawnSet(NPC, "soga_hair_color2", "111 64 0") 
            SpawnSet(NPC, "hair_highlight", "29 21 28")
            SpawnSet(NPC, "soga_hair_highlight", "29 21 28")
        elseif overall_look == 7 then -- Orange light golden high lights
            SpawnSet(NPC, "skin_color", "229 215 216")
            SpawnSet(NPC, "soga_skin_color", "229 215 216") 
            SpawnSet(NPC, "eye_color", "61 123 140")
            SpawnSet(NPC, "soga_eye_color", "61 123 140") 
            SpawnSet(NPC, "hair_type_color", "173 66 27")
            SpawnSet(NPC, "soga_hair_type_color", "173 66 27") 
            SpawnSet(NPC, "hair_face_color", "173 66 27")
            SpawnSet(NPC, "soga_hair_face_color", "173 66 27")
            SpawnSet(NPC, "hair_type_highlight_color", "83 58 8")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "83 58 8")
            SpawnSet(NPC, "hair_face_highlight_color", "83 58 8")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "83 58 8")
            SpawnSet(NPC, "hair_color1", "89 21 21")
            SpawnSet(NPC, "soga_hair_color1", "89 21 21") 
            SpawnSet(NPC, "hair_color2", "171 87 0")
            SpawnSet(NPC, "soga_hair_color2", "171 87 0") 
            SpawnSet(NPC, "hair_highlight", "56 33 26")
            SpawnSet(NPC, "soga_hair_highlight", "56 33 26") 
        elseif overall_look == 8 then -- Orange light golden high lights
            SpawnSet(NPC, "skin_color", "161 140 92")
            SpawnSet(NPC, "soga_skin_color", "161 140 92") 
            SpawnSet(NPC, "eye_color", "126 179 189")
            SpawnSet(NPC, "soga_eye_color", "126 179 189") 
            SpawnSet(NPC, "hair_type_color", "168 59 22")
            SpawnSet(NPC, "soga_hair_type_color", "168 59 22") 
            SpawnSet(NPC, "hair_face_color", "168 59 22")
            SpawnSet(NPC, "soga_hair_face_color", "168 59 22")
            SpawnSet(NPC, "hair_type_highlight_color", "84 0 0")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "84 0 0")
            SpawnSet(NPC, "hair_face_highlight_color", "84 0 0")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "84 0 0")
            SpawnSet(NPC, "hair_color1", "89 21 21")
            SpawnSet(NPC, "soga_hair_color1", "89 21 21") 
            SpawnSet(NPC, "hair_color2", "171 87 0")
            SpawnSet(NPC, "soga_hair_color2", "171 87 0") 
            SpawnSet(NPC, "hair_highlight", "109 14 49")
            SpawnSet(NPC, "soga_hair_highlight", "109 14 49") 
        elseif overall_look == 9 then -- Yellow bright
            SpawnSet(NPC, "skin_color", "155 156 156")
            SpawnSet(NPC, "soga_skin_color", "155 156 156") 
            SpawnSet(NPC, "eye_color", "49 100 115")
            SpawnSet(NPC, "soga_eye_color", "49 100 115") 
            SpawnSet(NPC, "hair_type_color", "228 182 25")
            SpawnSet(NPC, "soga_hair_type_color", "228 182 25") 
            SpawnSet(NPC, "hair_face_color", "228 182 25")
            SpawnSet(NPC, "soga_hair_face_color", "228 182 25")
            SpawnSet(NPC, "hair_type_highlight_color", "170 63 24")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "170 63 24")
            SpawnSet(NPC, "hair_face_highlight_color", "170 63 24")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "170 63 24")
            SpawnSet(NPC, "hair_color1", "246 219 114")
            SpawnSet(NPC, "soga_hair_color1", "246 219 114") 
            SpawnSet(NPC, "hair_color2", "187 136 62")
            SpawnSet(NPC, "soga_hair_color2", "187 136 62") 
            SpawnSet(NPC, "hair_highlight", "89 21 21")
            SpawnSet(NPC, "soga_hair_highlight", "89 21 21") 
        elseif overall_look == 10 then -- Brown golden highlights
            SpawnSet(NPC, "skin_color", "242 252 252")
            SpawnSet(NPC, "soga_skin_color", "242 252 252") 
            SpawnSet(NPC, "eye_color", "94 159 177")
            SpawnSet(NPC, "soga_eye_color", "94 159 177") 
            SpawnSet(NPC, "hair_type_color", "35 24 1")
            SpawnSet(NPC, "soga_hair_type_color", "35 24 1") 
            SpawnSet(NPC, "hair_face_color", "35 24 1")
            SpawnSet(NPC, "soga_hair_face_color", "35 24 1")
            SpawnSet(NPC, "hair_type_highlight_color", "100 70 10")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "100 70 10")
            SpawnSet(NPC, "hair_face_highlight_color", "100 70 10")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "100 70 10")
            SpawnSet(NPC, "hair_color1", "79 28 15")
            SpawnSet(NPC, "soga_hair_color1", "79 28 15") 
            SpawnSet(NPC, "hair_color2", "111 64 0")
            SpawnSet(NPC, "soga_hair_color2", "111 64 0") 
            SpawnSet(NPC, "hair_highlight", "56 33 26")
            SpawnSet(NPC, "soga_hair_highlight", "56 33 26")
        elseif overall_look == 11 then -- Yellow bright light
            SpawnSet(NPC, "skin_color", "240 204 208")
            SpawnSet(NPC, "soga_skin_color", "240 204 208") 
            SpawnSet(NPC, "eye_color", "121 176 189")
            SpawnSet(NPC, "soga_eye_color", "121 176 189") 
            SpawnSet(NPC, "hair_type_color", "229 182 26")
            SpawnSet(NPC, "soga_hair_type_color", "229 182 26") 
            SpawnSet(NPC, "hair_face_color", "229 182 26")
            SpawnSet(NPC, "soga_hair_face_color", "229 182 26")
            SpawnSet(NPC, "hair_type_highlight_color", "244 246 246")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "244 246 246")
            SpawnSet(NPC, "hair_face_highlight_color", "244 246 246")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "244 246 246")
            SpawnSet(NPC, "hair_color1", "246 219 114")
            SpawnSet(NPC, "soga_hair_color1", "246 219 114") 
            SpawnSet(NPC, "hair_color2", "187 136 62")
            SpawnSet(NPC, "soga_hair_color2", "187 136 62") 
            SpawnSet(NPC, "hair_highlight", "161 165 168")
            SpawnSet(NPC, "soga_hair_highlight", "161 165 168")
        elseif overall_look == 12 then -- Yellow bright
            SpawnSet(NPC, "skin_color", "224 204 159")
            SpawnSet(NPC, "soga_skin_color", "224 204 159") 
            SpawnSet(NPC, "eye_color", "43 69 43")
            SpawnSet(NPC, "soga_eye_color", "43 69 43") 
            SpawnSet(NPC, "hair_type_color", "201 142 16")
            SpawnSet(NPC, "soga_hair_type_color", "201 142 16") 
            SpawnSet(NPC, "hair_face_color", "201 142 16")
            SpawnSet(NPC, "soga_hair_face_color", "201 142 16")
            SpawnSet(NPC, "hair_type_highlight_color", "48 32 3")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "48 32 3")
            SpawnSet(NPC, "hair_face_highlight_color", "48 32 3")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "48 32 3")
            SpawnSet(NPC, "hair_color1", "209 131 22")
            SpawnSet(NPC, "soga_hair_color1", "209 131 22") 
            SpawnSet(NPC, "hair_color2", "199 150 48")
            SpawnSet(NPC, "soga_hair_color2", "199 150 48") 
            SpawnSet(NPC, "hair_highlight", "79 28 15")
            SpawnSet(NPC, "soga_hair_highlight", "79 28 15")
        elseif overall_look == 13 then -- Orange light yellow stripes
            SpawnSet(NPC, "skin_color", "105 105 105")
            SpawnSet(NPC, "soga_skin_color", "105 105 105") 
            SpawnSet(NPC, "eye_color", "29 59 47")
            SpawnSet(NPC, "soga_eye_color", "29 59 47") 
            SpawnSet(NPC, "hair_type_color", "100 70 10")
            SpawnSet(NPC, "soga_hair_type_color", "100 70 10") 
            SpawnSet(NPC, "hair_face_color", "100 70 10")
            SpawnSet(NPC, "soga_hair_face_color", "100 70 10")
            SpawnSet(NPC, "hair_type_highlight_color", "244 246 246")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "244 246 246")
            SpawnSet(NPC, "hair_face_highlight_color", "244 246 246")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "244 246 246")
            SpawnSet(NPC, "hair_color1", "56 33 26")
            SpawnSet(NPC, "soga_hair_color1", "56 33 26") 
            SpawnSet(NPC, "hair_color2", "94 59 11")
            SpawnSet(NPC, "soga_hair_color2", "94 59 11") 
            SpawnSet(NPC, "hair_highlight", "161 165 168")
            SpawnSet(NPC, "soga_hair_highlight", "161 165 168") 
        elseif overall_look == 14 then -- Brown dark
            SpawnSet(NPC, "skin_color", "101 67 52")
            SpawnSet(NPC, "soga_skin_color", "101 67 52") 
            SpawnSet(NPC, "eye_color", "37 77 88")
            SpawnSet(NPC, "soga_eye_color", "37 77 88") 
            SpawnSet(NPC, "hair_type_color", "18 9 1")
            SpawnSet(NPC, "soga_hair_type_color", "18 9 1") 
            SpawnSet(NPC, "hair_face_color", "18 9 1")
            SpawnSet(NPC, "soga_hair_face_color", "18 9 1")
            SpawnSet(NPC, "hair_type_highlight_color", "67 28 10")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "67 28 10")
            SpawnSet(NPC, "hair_face_highlight_color", "67 28 10")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "67 28 10")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        end
end

function DwarfCosmetics(NPC)
    local Type = GetModelType(NPC)
    local hair = 0
    
    if Type == 109 then
        hair = MakeRandomInt(1135,1140) -- 1133, 1136, 1137
        SpawnSet(NPC, "hair_type", hair)
        SpawnSet(NPC, "soga_hair_type", hair)
    else
        hair = MakeRandomInt(1135,1140) -- 1113, 1133, 1136
        SpawnSet(NPC, "hair_type", hair)
        SpawnSet(NPC, "soga_hair_type", hair)
    end
        
    local beard = MakeRandomInt(1164,1170) -- 1184, 1185, 1187, 1188, 1189, 1190
        SpawnSet(NPC, "facial_hair_type", beard)
        SpawnSet(NPC, "soga_facial_hair_type", beard)

    local overall_look = MakeRandomInt(15,15)

        if overall_look == 1 then -- Chestnut golden highlights
            SpawnSet(NPC, "skin_color", "227 219 200")
            SpawnSet(NPC, "soga_skin_color", "227 219 200") 
            SpawnSet(NPC, "eye_color", "53 34 13")
            SpawnSet(NPC, "soga_eye_color", "53 34 13") 
            SpawnSet(NPC, "hair_type_color", "24 10 2")
            SpawnSet(NPC, "soga_hair_type_color", "24 10 2") 
            SpawnSet(NPC, "hair_face_color", "24 10 2")
            SpawnSet(NPC, "soga_hair_face_color", "24 10 2")
            SpawnSet(NPC, "hair_type_highlight_color", "150 88 18")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "150 88 18")
            SpawnSet(NPC, "hair_face_highlight_color", "150 88 18")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "150 88 18")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 2 then -- Red orange 
            SpawnSet(NPC, "skin_color", "221 180 181")
            SpawnSet(NPC, "soga_skin_color", "221 180 181") 
            SpawnSet(NPC, "eye_color", "110 160 149")
            SpawnSet(NPC, "soga_eye_color", "110 160 149") 
            SpawnSet(NPC, "hair_type_color", "129 44 8")
            SpawnSet(NPC, "soga_hair_type_color", "129 44 8") 
            SpawnSet(NPC, "hair_face_color", "129 44 8")
            SpawnSet(NPC, "soga_hair_face_color", "129 44 8")
            SpawnSet(NPC, "hair_type_highlight_color", "155 64 24")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "155 64 24") 
            SpawnSet(NPC, "hair_face_highlight_color", "155 64 24")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "155 64 24")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 3 then -- Beige light with brown and white stribes
            SpawnSet(NPC, "skin_color", "245 248 246")
            SpawnSet(NPC, "soga_skin_color", "245 248 246") 
            SpawnSet(NPC, "eye_color", "131 163 133")
            SpawnSet(NPC, "soga_eye_color", "131 163 133") 
            SpawnSet(NPC, "hair_type_color", "247 239 212")
            SpawnSet(NPC, "soga_hair_type_color", "247 239 212") 
            SpawnSet(NPC, "hair_face_color", "247 239 212")
            SpawnSet(NPC, "soga_hair_face_color", "247 239 212")
            SpawnSet(NPC, "hair_type_highlight_color", "54 47 3")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "54 47 3") 
            SpawnSet(NPC, "hair_face_highlight_color", "54 47 3")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "54 47 3")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 4 then -- Orange
            SpawnSet(NPC, "skin_color", "201 155 130")
            SpawnSet(NPC, "soga_skin_color", "201 155 130") 
            SpawnSet(NPC, "eye_color", "38 75 60")
            SpawnSet(NPC, "soga_eye_color", "38 75 60") 
            SpawnSet(NPC, "hair_type_color", "146 60 12")
            SpawnSet(NPC, "soga_hair_type_color", "146 60 12") 
            SpawnSet(NPC, "hair_face_color", "146 60 12")
            SpawnSet(NPC, "soga_hair_face_color", "146 60 12")
            SpawnSet(NPC, "hair_type_highlight_color", "45 21 5")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "45 21 5") 
            SpawnSet(NPC, "hair_face_highlight_color", "45 21 5")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "45 21 5")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 5 then -- Red orange
            SpawnSet(NPC, "skin_color", "196 146 123")
            SpawnSet(NPC, "soga_skin_color", "196 146 123") 
            SpawnSet(NPC, "eye_color", "121 176 192")
            SpawnSet(NPC, "soga_eye_color", "121 176 192") 
            SpawnSet(NPC, "hair_type_color", "119 43 9")
            SpawnSet(NPC, "soga_hair_type_color", "119 43 9") 
            SpawnSet(NPC, "hair_face_color", "119 43 9")
            SpawnSet(NPC, "soga_hair_face_color", "119 43 9")
            SpawnSet(NPC, "hair_type_highlight_color", "66 28 9")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "66 28 9") 
            SpawnSet(NPC, "hair_face_highlight_color", "66 28 9")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "66 28 9")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 6 then -- Brown light
            SpawnSet(NPC, "skin_color", "241 210 210")
            SpawnSet(NPC, "soga_skin_color", "241 210 210") 
            SpawnSet(NPC, "eye_color", "99 161 170")
            SpawnSet(NPC, "soga_eye_color", "99 161 170") 
            SpawnSet(NPC, "hair_type_color", "99 79 32")
            SpawnSet(NPC, "soga_hair_type_color", "99 79 32") 
            SpawnSet(NPC, "hair_face_color", "99 79 32")
            SpawnSet(NPC, "soga_hair_face_color", "99 79 32")
            SpawnSet(NPC, "hair_type_highlight_color", "39 37 18")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "39 37 18") 
            SpawnSet(NPC, "hair_face_highlight_color", "39 37 18")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "39 37 18")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 7 then -- Grey dark beige
            SpawnSet(NPC, "skin_color", "219 228 220")
            SpawnSet(NPC, "soga_skin_color", "219 228 220") 
            SpawnSet(NPC, "eye_color", "32 67 73")
            SpawnSet(NPC, "soga_eye_color", "32 67 73") 
            SpawnSet(NPC, "hair_type_color", "126 126 125")
            SpawnSet(NPC, "soga_hair_type_color", "126 126 125") 
            SpawnSet(NPC, "hair_face_color", "126 126 125")
            SpawnSet(NPC, "soga_hair_face_color", "126 126 125")
            SpawnSet(NPC, "hair_type_highlight_color", "90 89 88")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "90 89 88") 
            SpawnSet(NPC, "hair_face_highlight_color", "90 89 88")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "90 89 88")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 8 then -- Beige light
            SpawnSet(NPC, "skin_color", "237 237 230")
            SpawnSet(NPC, "soga_skin_color", "237 237 230") 
            SpawnSet(NPC, "eye_color", "31 66 65")
            SpawnSet(NPC, "soga_eye_color", "31 66 65") 
            SpawnSet(NPC, "hair_type_color", "157 145 110")
            SpawnSet(NPC, "soga_hair_type_color", "157 145 110") 
            SpawnSet(NPC, "hair_face_color", "157 145 110")
            SpawnSet(NPC, "soga_hair_face_color", "157 145 110")
            SpawnSet(NPC, "hair_type_highlight_color", "71 49 21")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "71 49 21") 
            SpawnSet(NPC, "hair_face_highlight_color", "71 49 21")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "71 49 21")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 9 then -- Brown
            SpawnSet(NPC, "skin_color", "225 171 169")
            SpawnSet(NPC, "soga_skin_color", "225 171 169") 
            SpawnSet(NPC, "eye_color", "70 59 31")
            SpawnSet(NPC, "soga_eye_color", "70 59 31") 
            SpawnSet(NPC, "hair_type_color", "83 77 59")
            SpawnSet(NPC, "soga_hair_type_color", "83 77 59") 
            SpawnSet(NPC, "hair_face_color", "83 77 59")
            SpawnSet(NPC, "soga_hair_face_color", "83 77 59")
            SpawnSet(NPC, "hair_type_highlight_color", "75 47 0")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "75 47 0") 
            SpawnSet(NPC, "hair_face_highlight_color", "75 47 0")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "75 47 0")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 10 then -- Beige greyish
            SpawnSet(NPC, "skin_color", "228 189 174")
            SpawnSet(NPC, "soga_skin_color", "228 189 174") 
            SpawnSet(NPC, "eye_color", "138 174 156")
            SpawnSet(NPC, "soga_eye_color", "138 174 156") 
            SpawnSet(NPC, "hair_type_color", "233 195 179")
            SpawnSet(NPC, "soga_hair_type_color", "233 195 179") 
            SpawnSet(NPC, "hair_face_color", "233 195 179")
            SpawnSet(NPC, "soga_hair_face_color", "233 195 179")
            SpawnSet(NPC, "hair_type_highlight_color", "41 15 5")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "41 15 5") 
            SpawnSet(NPC, "hair_face_highlight_color", "41 15 5")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "41 15 5")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 11 then -- Brown dark
            SpawnSet(NPC, "skin_color", "215 194 160")
            SpawnSet(NPC, "soga_skin_color", "215 194 160") 
            SpawnSet(NPC, "eye_color", "73 42 13")
            SpawnSet(NPC, "soga_eye_color", "73 42 13") 
            SpawnSet(NPC, "hair_type_color", "25 18 6")
            SpawnSet(NPC, "soga_hair_type_color", "25 18 6") 
            SpawnSet(NPC, "hair_face_color", "25 18 6")
            SpawnSet(NPC, "soga_hair_face_color", "25 18 6")
            SpawnSet(NPC, "hair_type_highlight_color", "89 52 8")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "89 52 8") 
            SpawnSet(NPC, "hair_face_highlight_color", "89 52 8")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "89 52 8")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 12 then -- Brown dark
            SpawnSet(NPC, "skin_color", "197 141 123")
            SpawnSet(NPC, "soga_skin_color", "197 141 123") 
            SpawnSet(NPC, "eye_color", "104 166 185")
            SpawnSet(NPC, "soga_eye_color", "104 166 185") 
            SpawnSet(NPC, "hair_type_color", "39 19 4")
            SpawnSet(NPC, "soga_hair_type_color", "39 19 4") 
            SpawnSet(NPC, "hair_face_color", "39 19 4")
            SpawnSet(NPC, "soga_hair_face_color", "39 19 4")
            SpawnSet(NPC, "hair_type_highlight_color", "28 18 0")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "28 18 0") 
            SpawnSet(NPC, "hair_face_highlight_color", "28 18 0")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "28 18 0")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 13 then -- Brown light yellow stripes
            SpawnSet(NPC, "skin_color", "222 186 188")
            SpawnSet(NPC, "soga_skin_color", "222 186 188") 
            SpawnSet(NPC, "eye_color", "71 61 32")
            SpawnSet(NPC, "soga_eye_color", "71 61 32") 
            SpawnSet(NPC, "hair_type_color", "112 40 8")
            SpawnSet(NPC, "soga_hair_type_color", "112 40 8") 
            SpawnSet(NPC, "hair_face_color", "112 40 8")
            SpawnSet(NPC, "soga_hair_face_color", "112 40 8")
            SpawnSet(NPC, "hair_type_highlight_color", "228 218 132")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "228 218 132") 
            SpawnSet(NPC, "hair_face_highlight_color", "228 218 132")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "228 218 132")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 14 then -- Brown light yellow stripes
            SpawnSet(NPC, "skin_color", "200 185 153")
            SpawnSet(NPC, "soga_skin_color", "200 185 153") 
            SpawnSet(NPC, "eye_color", "130 182 197")
            SpawnSet(NPC, "soga_eye_color", "130 182 197") 
            SpawnSet(NPC, "hair_type_color", "58 45 18")
            SpawnSet(NPC, "soga_hair_type_color", "58 45 18") 
            SpawnSet(NPC, "hair_face_color", "58 45 18")
            SpawnSet(NPC, "soga_hair_face_color", "58 45 18")
            SpawnSet(NPC, "hair_type_highlight_color", "219 180 3")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "219 180 3") 
            SpawnSet(NPC, "hair_face_highlight_color", "219 180 3")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "219 180 3")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 15 then -- Brown dark
            SpawnSet(NPC, "skin_color", "239 206 205")
            SpawnSet(NPC, "soga_skin_color", "239 206 205") 
            SpawnSet(NPC, "eye_color", "45 93 84")
            SpawnSet(NPC, "soga_eye_color", "45 93 84") 
            SpawnSet(NPC, "hair_type_color", "40 21 12")
            SpawnSet(NPC, "soga_hair_type_color", "40 21 12") 
            SpawnSet(NPC, "hair_face_color", "40 21 12")
            SpawnSet(NPC, "soga_hair_face_color", "40 21 12")
            SpawnSet(NPC, "hair_type_highlight_color", "106 105 105")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "106 105 105") 
            SpawnSet(NPC, "hair_face_highlight_color", "106 105 105")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "106 105 105")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        end
end

function GnomeCosmetics(NPC)
    
    local hair = MakeRandomInt(1133,1140) -- 1133 (f|), 1136 (f|m), 1137 (f|) 1138 (|m)
    
        SpawnSet(NPC, "hair_type", hair)
        SpawnSet(NPC, "soga_hair_type", hair)

--[[    local trinket = MakeRandomInt(1185,1189) -- 0 
    local trinket_chance = MakeRandomInt(1,100)  

        if trinket_chance < 21 then
            SpawnSet(NPC, "facial_hair_type", "0")
            SpawnSet(NPC, "soga_facial_hair_type", "0")
        else
            SpawnSet(NPC, "facial_hair_type", trinket)
            SpawnSet(NPC, "soga_facial_hair_type", trinket)
        end--]]
        
    local overall_look = MakeRandomInt(5,5)

        if overall_look == 1 then -- Brown golden highlights
            SpawnSet(NPC, "skin_color", "230 217 211")
            SpawnSet(NPC, "soga_skin_color", "230 217 211") 
            SpawnSet(NPC, "eye_color", "40 84 88")
            SpawnSet(NPC, "soga_eye_color", "40 84 88") 
            SpawnSet(NPC, "hair_type_color", "41 32 19")
            SpawnSet(NPC, "soga_hair_type_color", "41 32 19") 
            SpawnSet(NPC, "hair_type_highlight_color", "200 71 37")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "200 71 37")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 2 then -- Black light
            SpawnSet(NPC, "skin_color", "253 254 254")
            SpawnSet(NPC, "soga_skin_color", "253 254 254") 
            SpawnSet(NPC, "eye_color", "158 197 204")
            SpawnSet(NPC, "soga_eye_color", "158 197 204") 
            SpawnSet(NPC, "hair_type_color", "77 103 103")
            SpawnSet(NPC, "soga_hair_type_color", "77 103 103") 
            SpawnSet(NPC, "hair_type_highlight_color", "119 46 8")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "119 46 8") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 3 then -- Brown dark
            SpawnSet(NPC, "skin_color", "245 214 215")
            SpawnSet(NPC, "soga_skin_color", "245 214 215") 
            SpawnSet(NPC, "eye_color", "108 80 37")
            SpawnSet(NPC, "soga_eye_color", "108 80 37") 
            SpawnSet(NPC, "hair_type_color", "45 50 40")
            SpawnSet(NPC, "soga_hair_type_color", "45 50 40") 
            SpawnSet(NPC, "hair_type_highlight_color", "125 78 1")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "125 78 1") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 4 then -- Caramel
            SpawnSet(NPC, "skin_color", "220 231 230")
            SpawnSet(NPC, "soga_skin_color", "220 231 230") 
            SpawnSet(NPC, "eye_color", "41 84 95")
            SpawnSet(NPC, "soga_eye_color", "41 84 95") 
            SpawnSet(NPC, "hair_type_color", "132 90 60")
            SpawnSet(NPC, "soga_hair_type_color", "132 90 60") 
            SpawnSet(NPC, "hair_type_highlight_color", "124 48 7")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "124 48 7") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 5 then -- Yellow beige light
            SpawnSet(NPC, "skin_color", "231 228 212")
            SpawnSet(NPC, "soga_skin_color", "231 228 212") 
            SpawnSet(NPC, "eye_color", "133 180 184")
            SpawnSet(NPC, "soga_eye_color", "133 180 184") 
            SpawnSet(NPC, "hair_type_color", "242 188 115")
            SpawnSet(NPC, "soga_hair_type_color", "242 188 115") 
            SpawnSet(NPC, "hair_type_highlight_color", "170 61 28")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "170 61 28") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        end
end