--[[
    Script Name    : SpawnScripts/qeynos_combined02/aTunarianscout.lua
    Script Author  : Rylec
    Script Date    : 2021.03.14 08:03:20
    Script Purpose : 
                   : 
--]]

function spawn(NPC)
    local model = MakeRandomInt(1,8)

        if model == 1 then
            SetModelType(NPC, "132") -- human female
            SpawnSet(NPC, "soga_model_type", "132")
            SpawnSet(NPC, "chest_type", "5529")
            SpawnSet(NPC, "legs_type", "5530")
            HumanCosmetics(NPC)
        elseif model == 2 then
            SetModelType(NPC, "134") -- human male
            SpawnSet(NPC, "soga_model_type", "134")
            SpawnSet(NPC, "chest_type", "5533")
            SpawnSet(NPC, "legs_type", "5534")
            HumanCosmetics(NPC)
        elseif model == 3 then
            SetModelType(NPC, "135") -- high elf female
            SpawnSet(NPC, "soga_model_type", "135")
            SpawnSet(NPC, "chest_type", "5521")
            SpawnSet(NPC, "legs_type", "5522")
            HighElfCosmetics(NPC)
        elseif model == 4 then
            SetModelType(NPC, "136") -- high elf male
            SpawnSet(NPC, "soga_model_type", "136")
            SpawnSet(NPC, "chest_type", "5525")
            SpawnSet(NPC, "legs_type", "5526")
            HighElfCosmetics(NPC)
        elseif model == 5 then
            SetModelType(NPC, "78") -- half elf male
            SpawnSet(NPC, "soga_model_type", "78")
            SpawnSet(NPC, "chest_type", "5509")
            SpawnSet(NPC, "legs_type", "5510")
            HalfElfCosmetics(NPC)
        elseif model == 6 then
            SetModelType(NPC, "79") -- half elf female
            SpawnSet(NPC, "soga_model_type", "79")
            SpawnSet(NPC, "chest_type", "5505")
            SpawnSet(NPC, "legs_type", "5506")
            HalfElfCosmetics(NPC)
        elseif model == 7 then
            SetModelType(NPC, "113") -- wood elf female
            SpawnSet(NPC, "soga_model_type", "113")
            SpawnSet(NPC, "chest_type", "5573")
            SpawnSet(NPC, "legs_type", "5574")
            WoodElfCosmetics(NPC)
        else
            SetModelType(NPC, "114") -- wood elf male
            SpawnSet(NPC, "soga_model_type", "114")
            SpawnSet(NPC, "chest_type", "5577")
            SpawnSet(NPC, "legs_type", "5578")
            WoodElfCosmetics(NPC)
        end

    SetEquipment(NPC, 2, 0)
end

function hailed(NPC, Spawn)
	FaceTarget(NPC, Spawn)
end

function respawn(NPC)
	spawn(NPC)
end

function HalfElfCosmetics(NPC)

    local hair = MakeRandomInt(1137,1140) -- 1125 (f|), 1127 (f|), 1133 (f|m), 1138 (f|)

        SpawnSet(NPC, "hair_type", hair)
        SpawnSet(NPC, "soga_hair_type", hair)
        
    local piercing = MakeRandomInt(1185,1191) -- 1166 (f|m), 1184 (f|), 1185 (|), 1187 (|m), 1191 (f|)
    local piercing_chance = MakeRandomInt(1,100)    

        if piercing_chance < 21 then
            SpawnSet(NPC, "facial_hair_type", "0")
            SpawnSet(NPC, "soga_facial_hair_type", "0")
        else
            SpawnSet(NPC, "facial_hair_type", piercing)
            SpawnSet(NPC, "soga_facial_hair_type", piercing)
        end

    local overall_look = MakeRandomInt(9,9)

        if overall_look == 1 then -- Bright white
            SpawnSet(NPC, "skin_color", "146 147 120")
            SpawnSet(NPC, "soga_skin_color", "146 147 120") 
            SpawnSet(NPC, "eye_color", "45 95 98")
            SpawnSet(NPC, "soga_eye_color", "45 95 98") 
            SpawnSet(NPC, "hair_type_color", "236 240 239")
            SpawnSet(NPC, "soga_hair_type_color", "236 240 239") 
            SpawnSet(NPC, "hair_type_highlight_color", "236 240 239")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "236 240 239") 
            SpawnSet(NPC, "hair_color1", "161 165 168")
            SpawnSet(NPC, "soga_hair_color1", "161 165 168") 
            SpawnSet(NPC, "hair_color2", "50 69 69")
            SpawnSet(NPC, "soga_hair_color2", "50 69 69") 
            SpawnSet(NPC, "hair_highlight", "246 219 114")
            SpawnSet(NPC, "soga_hair_highlight", "246 219 114") 
        elseif overall_look == 2 then -- Red dark and black/lilac
            SpawnSet(NPC, "skin_color", "217 193 160")
            SpawnSet(NPC, "soga_skin_color", "217 193 160") 
            SpawnSet(NPC, "eye_color", "135 162 128")
            SpawnSet(NPC, "soga_eye_color", "135 162 128") 
            SpawnSet(NPC, "hair_type_color", "91 7 6")
            SpawnSet(NPC, "soga_hair_type_color", "91 7 6") 
            SpawnSet(NPC, "hair_type_highlight_color", "40 34 51")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "40 34 51")
            SpawnSet(NPC, "hair_color1", "109 14 49")
            SpawnSet(NPC, "soga_hair_color1", "109 14 49") 
            SpawnSet(NPC, "hair_color2", "185 97 0")
            SpawnSet(NPC, "soga_hair_color2", "185 97 0") 
            SpawnSet(NPC, "hair_highlight", "43 36 70")
            SpawnSet(NPC, "soga_hair_highlight", "43 36 70") 
        elseif overall_look == 3 then -- Red and white
            SpawnSet(NPC, "skin_color", "85 87 87")
            SpawnSet(NPC, "soga_skin_color", "85 87 87") 
            SpawnSet(NPC, "eye_color", "94 125 77")
            SpawnSet(NPC, "soga_eye_color", "94 125 77") 
            SpawnSet(NPC, "hair_type_color", "119 147 147")
            SpawnSet(NPC, "soga_hair_type_color", "119 147 147") 
            SpawnSet(NPC, "hair_type_highlight_color", "84 0 0")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "84 0 0")
            SpawnSet(NPC, "hair_color1", "114 112 142")
            SpawnSet(NPC, "soga_hair_color1", "114 112 142") 
            SpawnSet(NPC, "hair_color2", "152 138 129")
            SpawnSet(NPC, "soga_hair_color2", "152 138 129") 
            SpawnSet(NPC, "hair_highlight", "109 14 49")
            SpawnSet(NPC, "soga_hair_highlight", "109 14 49") 
        elseif overall_look == 4 then -- Black dark
            SpawnSet(NPC, "skin_color", "213 187 157")
            SpawnSet(NPC, "soga_skin_color", "213 187 157") 
            SpawnSet(NPC, "eye_color", "76 60 30")
            SpawnSet(NPC, "soga_eye_color", "76 60 30") 
            SpawnSet(NPC, "hair_type_color", "0 0 0")
            SpawnSet(NPC, "soga_hair_type_color", "0 0 0") 
            SpawnSet(NPC, "hair_type_highlight_color", "0 0 0")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "0 0 0") 
            SpawnSet(NPC, "hair_color1", "38 22 21")
            SpawnSet(NPC, "soga_hair_color1", "38 22 21") 
            SpawnSet(NPC, "hair_color2", "120 50 0")
            SpawnSet(NPC, "soga_hair_color2", "120 50 0") 
            SpawnSet(NPC, "hair_highlight", "246 219 114")
            SpawnSet(NPC, "soga_hair_highlight", "246 219 114") 
        elseif overall_look == 5 then -- Yellow and Dark red
            SpawnSet(NPC, "skin_color", "213 187 157")
            SpawnSet(NPC, "soga_skin_color", "213 187 157") 
            SpawnSet(NPC, "eye_color", "89 134 93")
            SpawnSet(NPC, "soga_eye_color", "89 134 93") 
            SpawnSet(NPC, "hair_type_color", "84 0 0")
            SpawnSet(NPC, "soga_hair_type_color", "84 0 0") 
            SpawnSet(NPC, "hair_type_highlight_color", "223 181 20")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "223 181 20") 
            SpawnSet(NPC, "hair_color1", "109 14 49")
            SpawnSet(NPC, "soga_hair_color1", "109 14 49") 
            SpawnSet(NPC, "hair_color2", "185 97 0")
            SpawnSet(NPC, "soga_hair_color2", "185 97 0") 
            SpawnSet(NPC, "hair_highlight", "239 221 86")
            SpawnSet(NPC, "soga_hair_highlight", "239 221 86") 
        elseif overall_look == 6 then -- White and yellow
            SpawnSet(NPC, "skin_color", "213 187 157")
            SpawnSet(NPC, "soga_skin_color", "213 187 157") 
            SpawnSet(NPC, "eye_color", "76 60 30")
            SpawnSet(NPC, "soga_eye_color", "76 60 30") 
            SpawnSet(NPC, "hair_type_color", "244 246 246")
            SpawnSet(NPC, "soga_hair_type_color", "244 246 246") 
            SpawnSet(NPC, "hair_type_highlight_color", "233 184 31")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "233 184 31") 
            SpawnSet(NPC, "hair_color1", "161 165 168")
            SpawnSet(NPC, "soga_hair_color1", "161 165 168") 
            SpawnSet(NPC, "hair_color2", "50 69 69")
            SpawnSet(NPC, "soga_hair_color2", "50 69 69") 
            SpawnSet(NPC, "hair_highlight", "246 219 114")
            SpawnSet(NPC, "soga_hair_highlight", "246 219 114")
        elseif overall_look == 7 then -- Orange and red
            SpawnSet(NPC, "skin_color", "137 134 101")
            SpawnSet(NPC, "soga_skin_color", "137 134 101") 
            SpawnSet(NPC, "eye_color", "55 115 127")
            SpawnSet(NPC, "soga_eye_color", "55 115 127") 
            SpawnSet(NPC, "hair_type_color", "93 10 9")
            SpawnSet(NPC, "soga_hair_type_color", "93 10 9") 
            SpawnSet(NPC, "hair_type_highlight_color", "168 59 22")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "168 59 22") 
            SpawnSet(NPC, "hair_color1", "109 14 49")
            SpawnSet(NPC, "soga_hair_color1", "109 14 49") 
            SpawnSet(NPC, "hair_color2", "185 97 0")
            SpawnSet(NPC, "soga_hair_color2", "185 97 0") 
            SpawnSet(NPC, "hair_highlight", "89 21 21")
            SpawnSet(NPC, "soga_hair_highlight", "89 21 21") 
        elseif overall_look == 8 then -- Red light and black/lilac
            SpawnSet(NPC, "skin_color", "242 233 234")
            SpawnSet(NPC, "soga_skin_color", "242 233 234") 
            SpawnSet(NPC, "eye_color", "37 71 51")
            SpawnSet(NPC, "soga_eye_color", "37 71 51") 
            SpawnSet(NPC, "hair_type_color", "15 1 21")
            SpawnSet(NPC, "soga_hair_type_color", "15 1 21") 
            SpawnSet(NPC, "hair_type_highlight_color", "119 36 33")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "119 36 33") 
            SpawnSet(NPC, "hair_color1", "29 21 28")
            SpawnSet(NPC, "soga_hair_color1", "29 21 28") 
            SpawnSet(NPC, "hair_color2", "39 32 39")
            SpawnSet(NPC, "soga_hair_color2", "39 32 39") 
            SpawnSet(NPC, "hair_highlight", "91 21 51")
            SpawnSet(NPC, "soga_hair_highlight", "91 21 51") 
        elseif overall_look == 9 then -- White and yellow
            SpawnSet(NPC, "skin_color", "132 141 137")
            SpawnSet(NPC, "soga_skin_color", "132 141 137") 
            SpawnSet(NPC, "eye_color", "199 174 134")
            SpawnSet(NPC, "soga_eye_color", "199 174 134") 
            SpawnSet(NPC, "hair_type_color", "244 246 246")
            SpawnSet(NPC, "soga_hair_type_color", "244 246 246") 
            SpawnSet(NPC, "hair_type_highlight_color", "193 100 45")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "193 100 45") 
            SpawnSet(NPC, "hair_color1", "161 165 168")
            SpawnSet(NPC, "soga_hair_color1", "161 165 168") 
            SpawnSet(NPC, "hair_color2", "56 62 62")
            SpawnSet(NPC, "soga_hair_color2", "56 62 62") 
            SpawnSet(NPC, "hair_highlight", "105 26 26")
            SpawnSet(NPC, "soga_hair_highlight", "105 26 26")
        end
end

function WoodElfCosmetics(NPC)

    local hair = MakeRandomInt(1133,1139) -- 1113 (|m), 1130 (f|), 1131 (f|), 1133 (|m), 1136 (|m), 1137 (f|)

        SpawnSet(NPC, "hair_type", hair)
        SpawnSet(NPC, "soga_hair_type", hair)
        
    local overall_look = MakeRandomInt(12,12)

        if overall_look == 1 then -- Beige reddish light
            SpawnSet(NPC, "skin_color", "203 148 115")
            SpawnSet(NPC, "soga_skin_color", "203 148 115") 
            SpawnSet(NPC, "eye_color", "149 190 197")
            SpawnSet(NPC, "soga_eye_color", "149 190 197") 
            SpawnSet(NPC, "hair_type_color", "169 120 99")
            SpawnSet(NPC, "soga_hair_type_color", "169 120 99") 
            SpawnSet(NPC, "hair_type_highlight_color", "135 55 0")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "135 55 0") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 2 then -- Yellow dark
            SpawnSet(NPC, "skin_color", "217 193 160")
            SpawnSet(NPC, "soga_skin_color", "217 193 160") 
            SpawnSet(NPC, "eye_color", "202 188 158")
            SpawnSet(NPC, "soga_eye_color", "202 188 158") 
            SpawnSet(NPC, "hair_type_color", "172 148 51")
            SpawnSet(NPC, "soga_hair_type_color", "172 148 51") 
            SpawnSet(NPC, "hair_type_highlight_color", "4 1 0")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "4 1 0") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 3 then -- Yellow dark vers 2
            SpawnSet(NPC, "skin_color", "191 166 131")
            SpawnSet(NPC, "soga_skin_color", "191 166 131") 
            SpawnSet(NPC, "eye_color", "63 129 143")
            SpawnSet(NPC, "soga_eye_color", "63 129 143") 
            SpawnSet(NPC, "hair_type_color", "166 126 37")
            SpawnSet(NPC, "soga_hair_type_color", "166 126 37") 
            SpawnSet(NPC, "hair_type_highlight_color", "84 41 0")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "84 41 0") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 4 then -- Beige reddish medium bright highlight
            SpawnSet(NPC, "skin_color", "202 180 137")
            SpawnSet(NPC, "soga_skin_color", "202 180 137") 
            SpawnSet(NPC, "eye_color", "44 93 88")
            SpawnSet(NPC, "soga_eye_color", "44 93 88") 
            SpawnSet(NPC, "hair_type_color", "151 81 46")
            SpawnSet(NPC, "soga_hair_type_color", "151 81 46") 
            SpawnSet(NPC, "hair_type_highlight_color", "137 120 98")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "137 120 98")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 5 then -- Beige reddish medium grey highlight
            SpawnSet(NPC, "skin_color", "191 166 131")
            SpawnSet(NPC, "soga_skin_color", "191 166 131") 
            SpawnSet(NPC, "eye_color", "52 112 112")
            SpawnSet(NPC, "soga_eye_color", "52 112 112") 
            SpawnSet(NPC, "hair_type_color", "139 80 51")
            SpawnSet(NPC, "soga_hair_type_color", "139 80 51") 
            SpawnSet(NPC, "hair_type_highlight_color", "84 84 83")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "84 84 83")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")             
        elseif overall_look == 6 then -- White light grey
            SpawnSet(NPC, "skin_color", "172 106 62")
            SpawnSet(NPC, "soga_skin_color", "172 106 62") 
            SpawnSet(NPC, "eye_color", "157 187 169")
            SpawnSet(NPC, "soga_eye_color", "157 187 169") 
            SpawnSet(NPC, "hair_type_color", "212 210 207")
            SpawnSet(NPC, "soga_hair_type_color", "212 210 207") 
            SpawnSet(NPC, "hair_type_highlight_color", "125 66 4")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "125 66 4")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 7 then -- Beige light
            SpawnSet(NPC, "skin_color", "189 168 120")
            SpawnSet(NPC, "soga_skin_color", "189 168 120") 
            SpawnSet(NPC, "eye_color", "43 87 100")
            SpawnSet(NPC, "soga_eye_color", "43 87 100") 
            SpawnSet(NPC, "hair_type_color", "178 155 145")
            SpawnSet(NPC, "soga_hair_type_color", "178 155 145") 
            SpawnSet(NPC, "hair_type_highlight_color", "114 106 39")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "114 106 39")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 8 then -- Yellow beige light
            SpawnSet(NPC, "skin_color", "168 119 69")
            SpawnSet(NPC, "soga_skin_color", "168 119 69") 
            SpawnSet(NPC, "eye_color", "126 178 194")
            SpawnSet(NPC, "soga_eye_color", "126 178 194") 
            SpawnSet(NPC, "hair_type_color", "208 197 90")
            SpawnSet(NPC, "soga_hair_type_color", "208 197 90") 
            SpawnSet(NPC, "hair_type_highlight_color", "22 8 2")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "22 8 2")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 9 then -- Yellow warm gold
            SpawnSet(NPC, "skin_color", "177 117 83")
            SpawnSet(NPC, "soga_skin_color", "177 117 83") 
            SpawnSet(NPC, "eye_color", "188 176 141")
            SpawnSet(NPC, "soga_eye_color", "188 176 141") 
            SpawnSet(NPC, "hair_type_color", "158 120 35")
            SpawnSet(NPC, "soga_hair_type_color", "158 120 35") 
            SpawnSet(NPC, "hair_type_highlight_color", "114 94 0")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "114 94 0")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 10 then -- Yellow light
            SpawnSet(NPC, "skin_color", "190 142 104")
            SpawnSet(NPC, "soga_skin_color", "190 142 104") 
            SpawnSet(NPC, "eye_color", "139 179 169")
            SpawnSet(NPC, "soga_eye_color", "139 179 169") 
            SpawnSet(NPC, "hair_type_color", "215 203 91")
            SpawnSet(NPC, "soga_hair_type_color", "215 203 91") 
            SpawnSet(NPC, "hair_type_highlight_color", "84 70 0")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "84 70 0")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 11 then -- Yellow dark golden
            SpawnSet(NPC, "skin_color", "182 139 92")
            SpawnSet(NPC, "soga_skin_color", "182 139 92") 
            SpawnSet(NPC, "eye_color", "55 112 129")
            SpawnSet(NPC, "soga_eye_color", "55 112 129") 
            SpawnSet(NPC, "hair_type_color", "160 114 32")
            SpawnSet(NPC, "soga_hair_type_color", "160 114 32") 
            SpawnSet(NPC, "hair_type_highlight_color", "61 28 0")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "61 28 0")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 12 then -- White and orange
            SpawnSet(NPC, "skin_color", "183 150 105")
            SpawnSet(NPC, "soga_skin_color", "183 150 105") 
            SpawnSet(NPC, "eye_color", "163 182 156")
            SpawnSet(NPC, "soga_eye_color", "163 182 156") 
            SpawnSet(NPC, "hair_type_color", "171 166 94")
            SpawnSet(NPC, "soga_hair_type_color", "171 166 94") 
            SpawnSet(NPC, "hair_type_highlight_color", "39 20 0")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "39 20 0")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        end
end

function HighElfCosmetics(NPC)

    local hair = MakeRandomInt(1133,1140)  -- 1133 (f|m), 1136 (f|), 1137 (f|m)

        SpawnSet(NPC, "hair_type", hair)
        SpawnSet(NPC, "soga_hair_type", hair)

    local overall_look = MakeRandomInt(15,15)

        if overall_look == 1 then -- White
            SpawnSet(NPC, "skin_color", "235 243 243")
            SpawnSet(NPC, "soga_skin_color", "235 243 243") 
            SpawnSet(NPC, "eye_color", "112 168 180")
            SpawnSet(NPC, "soga_eye_color", "112 168 180") 
            SpawnSet(NPC, "hair_type_color", "247 240 227")
            SpawnSet(NPC, "soga_hair_type_color", "247 240 227") 
            SpawnSet(NPC, "hair_type_highlight_color", "14 11 9")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "14 11 9")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 2 then -- Light grey
            SpawnSet(NPC, "skin_color", "209 181 133")
            SpawnSet(NPC, "soga_skin_color", "209 181 133") 
            SpawnSet(NPC, "eye_color", "69 82 46")
            SpawnSet(NPC, "soga_eye_color", "69 82 46") 
            SpawnSet(NPC, "hair_type_color", "219 219 216")
            SpawnSet(NPC, "soga_hair_type_color", "219 219 216") 
            SpawnSet(NPC, "hair_type_highlight_color", "54 22 8")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "54 22 8") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 3 then -- Very light yellow
            SpawnSet(NPC, "skin_color", "240 249 246")
            SpawnSet(NPC, "soga_skin_color", "240 249 246") 
            SpawnSet(NPC, "eye_color", "96 160 174")
            SpawnSet(NPC, "soga_eye_color", "96 160 174") 
            SpawnSet(NPC, "hair_type_color", "214 184 120")
            SpawnSet(NPC, "soga_hair_type_color", "214 184 120") 
            SpawnSet(NPC, "hair_type_highlight_color", "65 61 27")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "65 61 27") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 4 then -- Light yellow
            SpawnSet(NPC, "skin_color", "255 255 255")
            SpawnSet(NPC, "soga_skin_color", "255 255 255") 
            SpawnSet(NPC, "eye_color", "58 62 34")
            SpawnSet(NPC, "soga_eye_color", "58 62 34") 
            SpawnSet(NPC, "hair_type_color", "213 215 126")
            SpawnSet(NPC, "soga_hair_type_color", "213 215 126") 
            SpawnSet(NPC, "hair_type_highlight_color", "54 32 1")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "54 32 1") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 5 then -- Bright yellow
            SpawnSet(NPC, "skin_color", "193 199 199")
            SpawnSet(NPC, "soga_skin_color", "193 199 199") 
            SpawnSet(NPC, "eye_color", "71 57 30")
            SpawnSet(NPC, "soga_eye_color", "71 57 30") 
            SpawnSet(NPC, "hair_type_color", "236 195 50")
            SpawnSet(NPC, "soga_hair_type_color", "236 195 50") 
            SpawnSet(NPC, "hair_type_highlight_color", "65 37 3")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "65 37 3") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 6 then -- Light yellow vers 2
            SpawnSet(NPC, "skin_color", "193 199 199")
            SpawnSet(NPC, "soga_skin_color", "193 199 199") 
            SpawnSet(NPC, "eye_color", "71 57 30")
            SpawnSet(NPC, "soga_eye_color", "71 57 30") 
            SpawnSet(NPC, "hair_type_color", "236 233 113")
            SpawnSet(NPC, "soga_hair_type_color", "236 195 50") 
            SpawnSet(NPC, "hair_type_highlight_color", "104 102 100")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "65 37 3") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 7 then -- Dark yellow
            SpawnSet(NPC, "skin_color", "240 249 246")
            SpawnSet(NPC, "soga_skin_color", "240 249 246") 
            SpawnSet(NPC, "eye_color", "105 85 44")
            SpawnSet(NPC, "soga_eye_color", "105 85 44") 
            SpawnSet(NPC, "hair_type_color", "211 157 3")
            SpawnSet(NPC, "soga_hair_type_color", "211 157 3") 
            SpawnSet(NPC, "hair_type_highlight_color", "125 50 1")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "125 50 1") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 8 then -- Orange dark
            SpawnSet(NPC, "skin_color", "218 229 229")
            SpawnSet(NPC, "soga_skin_color", "218 229 229") 
            SpawnSet(NPC, "eye_color", "102 70 30")
            SpawnSet(NPC, "soga_eye_color", "102 70 30") 
            SpawnSet(NPC, "hair_type_color", "219 136 25")
            SpawnSet(NPC, "soga_hair_type_color", "219 136 25") 
            SpawnSet(NPC, "hair_type_highlight_color", "59 54 48")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "59 54 48") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 9 then -- Orange light
            SpawnSet(NPC, "skin_color", "225 232 227")
            SpawnSet(NPC, "soga_skin_color", "225 232 227") 
            SpawnSet(NPC, "eye_color", "200 175 137")
            SpawnSet(NPC, "soga_eye_color", "200 175 137") 
            SpawnSet(NPC, "hair_type_color", "220 138 23")
            SpawnSet(NPC, "soga_hair_type_color", "220 138 23") 
            SpawnSet(NPC, "hair_type_highlight_color", "113 39 21")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "113 39 21") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 10 then -- White yellow light
            SpawnSet(NPC, "skin_color", "221 225 225")
            SpawnSet(NPC, "soga_skin_color", "221 225 225") 
            SpawnSet(NPC, "eye_color", "138 174 156")
            SpawnSet(NPC, "soga_eye_color", "138 174 156") 
            SpawnSet(NPC, "hair_type_color", "222 210 186")
            SpawnSet(NPC, "soga_hair_type_color", "222 210 186") 
            SpawnSet(NPC, "hair_type_highlight_color", "118 116 114")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "118 116 114") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 11 then -- Yellow light mat
            SpawnSet(NPC, "skin_color", "223 183 127")
            SpawnSet(NPC, "soga_skin_color", "223 183 127") 
            SpawnSet(NPC, "eye_color", "53 109 120")
            SpawnSet(NPC, "soga_eye_color", "53 109 120") 
            SpawnSet(NPC, "hair_type_color", "224 221 88")
            SpawnSet(NPC, "soga_hair_type_color", "224 221 88") 
            SpawnSet(NPC, "hair_type_highlight_color", "107 54 9")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "107 54 9") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 12 then -- Yellow 
            SpawnSet(NPC, "skin_color", "221 228 228")
            SpawnSet(NPC, "soga_skin_color", "221 228 228") 
            SpawnSet(NPC, "eye_color", "108 147 112")
            SpawnSet(NPC, "soga_eye_color", "108 147 112") 
            SpawnSet(NPC, "hair_type_color", "224 223 107")
            SpawnSet(NPC, "soga_hair_type_color", "224 223 107") 
            SpawnSet(NPC, "hair_type_highlight_color", "145 129 21")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "145 129 21") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 13 then -- Yellow light mat
            SpawnSet(NPC, "skin_color", "213 179 131")
            SpawnSet(NPC, "soga_skin_color", "213 179 131") 
            SpawnSet(NPC, "eye_color", "46 93 108")
            SpawnSet(NPC, "soga_eye_color", "46 93 108") 
            SpawnSet(NPC, "hair_type_color", "207 195 0")
            SpawnSet(NPC, "soga_hair_type_color", "207 195 0") 
            SpawnSet(NPC, "hair_type_highlight_color", "136 54 22")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "136 54 22") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 14 then -- Yellow light 
            SpawnSet(NPC, "skin_color", "253 254 254")
            SpawnSet(NPC, "soga_skin_color", "253 254 254") 
            SpawnSet(NPC, "eye_color", "139 185 192")
            SpawnSet(NPC, "soga_eye_color", "139 185 192") 
            SpawnSet(NPC, "hair_type_color", "209 211 130")
            SpawnSet(NPC, "soga_hair_type_color", "209 211 130") 
            SpawnSet(NPC, "hair_type_highlight_color", "105 91 74")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "105 91 74") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 15 then -- Yellow golden dark 
            SpawnSet(NPC, "skin_color", "235 205 162")
            SpawnSet(NPC, "soga_skin_color", "235 205 162") 
            SpawnSet(NPC, "eye_color", "145 190 203")
            SpawnSet(NPC, "soga_eye_color", "145 190 203") 
            SpawnSet(NPC, "hair_type_color", "214 158 10")
            SpawnSet(NPC, "soga_hair_type_color", "214 158 10") 
            SpawnSet(NPC, "hair_type_highlight_color", "84 58 25")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "84 58 25") 
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        end
end

function HumanCosmetics(NPC)

    local hair = MakeRandomInt(1121,1140)

        SpawnSet(NPC, "hair_type", hair)
        SpawnSet(NPC, "soga_hair_type", hair)

    local beard = MakeRandomInt(1164,1191)
    local beard_chance = MakeRandomInt(1,100)    

        if beard_chance < 51 then
            SpawnSet(NPC, "facial_hair_type", "0")
            SpawnSet(NPC, "soga_facial_hair_type", "0")
        else
            SpawnSet(NPC, "facial_hair_type", beard)
            SpawnSet(NPC, "soga_facial_hair_type", beard)
        end

    local overall_look = MakeRandomInt(1,14)
 
        if overall_look == 1 then -- Bright yellow
            SpawnSet(NPC, "skin_color", "206 162 137")
            SpawnSet(NPC, "soga_skin_color", "206 162 137") 
            SpawnSet(NPC, "eye_color", "47 100 102")
            SpawnSet(NPC, "soga_eye_color", "47 100 102") 
            SpawnSet(NPC, "hair_type_color", "194 164 6")
            SpawnSet(NPC, "soga_hair_type_color", "194 164 6") 
            SpawnSet(NPC, "hair_face_color", "194 164 6")
            SpawnSet(NPC, "soga_hair_face_color", "194 164 6")
            SpawnSet(NPC, "hair_type_highlight_color", "188 168 37")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "188 168 37") 
            SpawnSet(NPC, "hair_face_highlight_color", "188 168 37")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "188 168 37")
        elseif overall_look == 2 then -- Extra light chestnut (towards yellow)
            SpawnSet(NPC, "skin_color", "241 245 221")
            SpawnSet(NPC, "soga_skin_color", "241 245 221") 
            SpawnSet(NPC, "eye_color", "38 65 40")
            SpawnSet(NPC, "soga_eye_color", "38 65 40") 
            SpawnSet(NPC, "hair_type_color", "100 70 10")
            SpawnSet(NPC, "soga_hair_type_color", "100 70 10") 
            SpawnSet(NPC, "hair_face_color", "100 70 10")
            SpawnSet(NPC, "soga_hair_face_color", "100 70 10")
            SpawnSet(NPC, "hair_type_highlight_color", "231 170 26")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "231 170 26") 
            SpawnSet(NPC, "hair_face_highlight_color", "231 170 26")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "231 170 26")
            SpawnSet(NPC, "hair_color1", "56 33 26")
            SpawnSet(NPC, "soga_hair_color1", "56 33 26") 
            SpawnSet(NPC, "hair_color2", "94 59 11")
            SpawnSet(NPC, "soga_hair_color2", "94 59 11") 
            SpawnSet(NPC, "hair_highlight", "200 165 96")
            SpawnSet(NPC, "soga_hair_highlight", "200 165 96")  
        elseif overall_look == 3 then -- Light orange
            SpawnSet(NPC, "skin_color", "210 188 159")
            SpawnSet(NPC, "soga_skin_color", "210 188 159") 
            SpawnSet(NPC, "eye_color", "74 130 98")
            SpawnSet(NPC, "soga_eye_color", "74 130 98") 
            SpawnSet(NPC, "hair_type_color", "184 128 10")
            SpawnSet(NPC, "soga_hair_type_color", "184 128 10") 
            SpawnSet(NPC, "hair_face_color", "184 128 10")
            SpawnSet(NPC, "soga_hair_face_color", "184 128 10")
            SpawnSet(NPC, "hair_type_highlight_color", "37 10 14")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "37 10 14") 
            SpawnSet(NPC, "hair_face_highlight_color", "37 10 14")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "37 10 14")
            SpawnSet(NPC, "hair_color1", "213 84 34")
            SpawnSet(NPC, "soga_hair_color1", "213 84 34") 
            SpawnSet(NPC, "hair_color2", "2 0 0")
            SpawnSet(NPC, "soga_hair_color2", "2 0 0") 
        elseif overall_look == 4 then -- Orange with bright highlights
            SpawnSet(NPC, "skin_color", "234 244 244")
            SpawnSet(NPC, "soga_skin_color", "234 244 244") 
            SpawnSet(NPC, "eye_color", "37 76 88")
            SpawnSet(NPC, "soga_eye_color", "37 76 88") 
            SpawnSet(NPC, "hair_type_color", "121 38 35")
            SpawnSet(NPC, "soga_hair_type_color", "121 38 35") 
            SpawnSet(NPC, "hair_face_color", "121 38 35")
            SpawnSet(NPC, "soga_hair_face_color", "121 38 35")
            SpawnSet(NPC, "hair_type_highlight_color", "233 184 31")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "233 184 31") 
            SpawnSet(NPC, "hair_face_highlight_color", "233 184 31")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "233 184 31")
            SpawnSet(NPC, "hair_color1", "91 21 51")
            SpawnSet(NPC, "soga_hair_color1", "91 21 51") 
            SpawnSet(NPC, "hair_color2", "159 88 0")
            SpawnSet(NPC, "soga_hair_color2", "159 88 0") 
            SpawnSet(NPC, "hair_highlight", "246 219 114")
            SpawnSet(NPC, "soga_hair_highlight", "246 219 114") 
        elseif overall_look == 5 then -- Light chestnut
            SpawnSet(NPC, "skin_color", "245 249 245")
            SpawnSet(NPC, "soga_skin_color", "245 249 245") 
            SpawnSet(NPC, "eye_color", "43 70 43")
            SpawnSet(NPC, "soga_eye_color", "43 70 43") 
            SpawnSet(NPC, "hair_type_color", "37 22 5")
            SpawnSet(NPC, "soga_hair_type_color", "37 22 5") 
            SpawnSet(NPC, "hair_face_color", "37 22 5")
            SpawnSet(NPC, "soga_hair_face_color", "37 22 5")
            SpawnSet(NPC, "hair_type_highlight_color", "121 38 35")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "121 38 35") 
            SpawnSet(NPC, "hair_face_highlight_color", "121 38 35")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "121 38 35")
            SpawnSet(NPC, "hair_color1", "79 28 15")
            SpawnSet(NPC, "soga_hair_color1", "79 28 15") 
            SpawnSet(NPC, "hair_color2", "111 64 0")
            SpawnSet(NPC, "soga_hair_color2", "111 64 0") 
            SpawnSet(NPC, "hair_highlight", "91 21 51")
            SpawnSet(NPC, "soga_hair_highlight", "91 21 51")  
        elseif overall_look == 6 then -- Chestnut
            SpawnSet(NPC, "skin_color", "241 245 221")
            SpawnSet(NPC, "soga_skin_color", "241 245 221") 
            SpawnSet(NPC, "eye_color", "102 154 140")
            SpawnSet(NPC, "soga_eye_color", "102 154 140") 
            SpawnSet(NPC, "hair_type_color", "0 0 0")
            SpawnSet(NPC, "soga_hair_type_color", "0 0 0") 
            SpawnSet(NPC, "hair_face_color", "0 0 0")
            SpawnSet(NPC, "soga_hair_face_color", "0 0 0")
            SpawnSet(NPC, "hair_type_highlight_color", "15 1 21")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "15 1 21") 
            SpawnSet(NPC, "hair_face_highlight_color", "15 1 21")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "15 1 21")
            SpawnSet(NPC, "hair_color1", "38 22 21")
            SpawnSet(NPC, "soga_hair_color1", "38 22 21") 
            SpawnSet(NPC, "hair_color2", "120 50 0")
            SpawnSet(NPC, "soga_hair_color2", "120 50 0") 
            SpawnSet(NPC, "hair_highlight", "29 21 28")
            SpawnSet(NPC, "soga_hair_highlight", "29 21 28") 
        elseif overall_look == 7 then -- Chestnut and brown skin
            SpawnSet(NPC, "skin_color", "46 35 12")
            SpawnSet(NPC, "soga_skin_color", "46 35 12") 
            SpawnSet(NPC, "eye_color", "105 85 44")
            SpawnSet(NPC, "soga_eye_color", "105 85 44") 
            SpawnSet(NPC, "hair_type_color", "40 20 7")
            SpawnSet(NPC, "soga_hair_type_color", "40 20 7") 
            SpawnSet(NPC, "hair_face_color", "40 20 7")
            SpawnSet(NPC, "soga_hair_face_color", "40 20 7")
            SpawnSet(NPC, "hair_type_highlight_color", "47 42 59")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "47 42 59") 
            SpawnSet(NPC, "hair_face_highlight_color", "47 42 59")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "47 42 59")
        elseif overall_look == 8 then -- Dark brown
            SpawnSet(NPC, "skin_color", "176 156 105")
            SpawnSet(NPC, "soga_skin_color", "176 156 105") 
            SpawnSet(NPC, "eye_color", "67 132 116")
            SpawnSet(NPC, "soga_eye_color", "67 132 116") 
            SpawnSet(NPC, "hair_type_color", "33 24 12")
            SpawnSet(NPC, "soga_hair_type_color", "33 24 12") 
            SpawnSet(NPC, "hair_face_color", "33 24 12")
            SpawnSet(NPC, "soga_hair_face_color", "33 24 12")
            SpawnSet(NPC, "hair_type_highlight_color", "11 6 1")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "11 6 1") 
            SpawnSet(NPC, "hair_face_highlight_color", "11 6 1")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "11 6 1")
        elseif overall_look == 9 then -- Dark brown and brown skin
            SpawnSet(NPC, "skin_color", "46 35 12")
            SpawnSet(NPC, "soga_skin_color", "46 35 12") 
            SpawnSet(NPC, "eye_color", "105 85 44")
            SpawnSet(NPC, "soga_eye_color", "105 85 44") 
            SpawnSet(NPC, "hair_type_color", "33 24 12")
            SpawnSet(NPC, "soga_hair_type_color", "33 24 12") 
            SpawnSet(NPC, "hair_face_color", "33 24 12")
            SpawnSet(NPC, "soga_hair_face_color", "33 24 12")
            SpawnSet(NPC, "hair_type_highlight_color", "11 6 1")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "11 6 1") 
            SpawnSet(NPC, "hair_face_highlight_color", "11 6 1")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "11 6 1")
        elseif overall_look == 10 then -- Lige grey towards white
            SpawnSet(NPC, "skin_color", "181 132 94")
            SpawnSet(NPC, "soga_skin_color", "181 132 94") 
            SpawnSet(NPC, "eye_color", "31 68 69")
            SpawnSet(NPC, "soga_eye_color", "31 68 69") 
            SpawnSet(NPC, "hair_type_color", "213 209 159")
            SpawnSet(NPC, "soga_hair_type_color", "213 209 159") 
            SpawnSet(NPC, "hair_face_color", "213 209 159")
            SpawnSet(NPC, "soga_hair_face_color", "213 209 159")
            SpawnSet(NPC, "hair_type_highlight_color", "56 40 19")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "56 40 19") 
            SpawnSet(NPC, "hair_face_highlight_color", "56 40 19")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "56 40 19")
        elseif overall_look == 11 then -- Dark grey 
            SpawnSet(NPC, "skin_color", "186 191 170")
            SpawnSet(NPC, "soga_skin_color", "186 191 170") 
            SpawnSet(NPC, "eye_color", "38 77 88")
            SpawnSet(NPC, "soga_eye_color", "38 77 88") 
            SpawnSet(NPC, "hair_type_color", "59 58 73")
            SpawnSet(NPC, "soga_hair_type_color", "59 58 73") 
            SpawnSet(NPC, "hair_face_color", "59 58 73")
            SpawnSet(NPC, "soga_hair_face_color", "59 58 73")
            SpawnSet(NPC, "hair_type_highlight_color", "119 147 147")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "119 147 147") 
            SpawnSet(NPC, "hair_face_highlight_color", "119 147 147")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "119 147 147")
            SpawnSet(NPC, "hair_color1", "43 36 70")
            SpawnSet(NPC, "soga_hair_color1", "43 36 70") 
            SpawnSet(NPC, "hair_color2", "64 76 74")
            SpawnSet(NPC, "soga_hair_color2", "64 76 74")
            SpawnSet(NPC, "hair_highlight", "114 112 142")
            SpawnSet(NPC, "soga_hair_highlight", "114 112 142")
        elseif overall_look == 12 then -- Dark grey and brown skin
            SpawnSet(NPC, "skin_color", "46 35 12")
            SpawnSet(NPC, "soga_skin_color", "46 35 12") 
            SpawnSet(NPC, "eye_color", "105 85 44")
            SpawnSet(NPC, "soga_eye_color", "105 85 44") 
            SpawnSet(NPC, "hair_type_color", "59 58 73")
            SpawnSet(NPC, "soga_hair_type_color", "59 58 73") 
            SpawnSet(NPC, "hair_face_color", "59 58 73")
            SpawnSet(NPC, "soga_hair_face_color", "59 58 73")
            SpawnSet(NPC, "hair_type_highlight_color", "119 147 147")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "119 147 147") 
            SpawnSet(NPC, "hair_face_highlight_color", "119 147 147")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "119 147 147")
            SpawnSet(NPC, "hair_color1", "43 36 70")
            SpawnSet(NPC, "soga_hair_color1", "43 36 70") 
            SpawnSet(NPC, "hair_color2", "64 76 74")
            SpawnSet(NPC, "soga_hair_color2", "64 76 74")
            SpawnSet(NPC, "hair_highlight", "114 112 142")
            SpawnSet(NPC, "soga_hair_highlight", "114 112 142")
        elseif overall_look == 13 then -- Black with white highlights
            SpawnSet(NPC, "skin_color", "179 188 188")
            SpawnSet(NPC, "soga_skin_color", "179 188 188") 
            SpawnSet(NPC, "eye_color", "105 165 179")
            SpawnSet(NPC, "soga_eye_color", "105 165 179") 
            SpawnSet(NPC, "hair_type_color", "15 1 21")
            SpawnSet(NPC, "soga_hair_type_color", "15 1 21") 
            SpawnSet(NPC, "hair_face_color", "15 1 21")
            SpawnSet(NPC, "soga_hair_face_color", "15 1 21")
            SpawnSet(NPC, "hair_type_highlight_color", "211 220 220")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "211 220 220") 
            SpawnSet(NPC, "hair_face_highlight_color", "211 220 220")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "211 220 220")
            SpawnSet(NPC, "hair_color1", "29 21 28")
            SpawnSet(NPC, "soga_hair_color1", "29 21 28") 
            SpawnSet(NPC, "hair_color2", "39 32 39")
            SpawnSet(NPC, "soga_hair_color2", "39 32 39")
            SpawnSet(NPC, "hair_highlight", "161 165 168")
            SpawnSet(NPC, "soga_hair_highlight", "161 165 168")
         else -- Light black
            SpawnSet(NPC, "skin_color", "176 156 105")
            SpawnSet(NPC, "soga_skin_color", "176 156 105") 
            SpawnSet(NPC, "eye_color", "67 132 116")
            SpawnSet(NPC, "soga_eye_color", "67 132 116") 
            SpawnSet(NPC, "hair_type_color", "39 50 50")
            SpawnSet(NPC, "soga_hair_type_color", "39 50 50") 
            SpawnSet(NPC, "hair_face_color", "39 50 50")
            SpawnSet(NPC, "soga_hair_face_color", "39 50 50")
            SpawnSet(NPC, "hair_type_highlight_color", "18 11 0")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "18 11 0") 
            SpawnSet(NPC, "hair_face_highlight_color", "18 11 0")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "18 11 0")
        end
end

