--[[
	Script Name	: SpawnScripts/QeynosHarbor/QueenAntoniaBayle.lua
	Script Purpose	: Queen Antonia Bayle 
	Script Author	: Cynnar
	Script Date	: 2020.04.12
	Script Notes	: Auto-Generated Conversation from PacketParser Data
--]]

function spawn(NPC)
	SetPlayerProximityFunction(NPC, 10, "InRange", "LeaveRange")
end

function respawn(NPC)
	spawn(NPC)
end

function InRange(NPC, Spawn)
	local playmsg = math.random(1,100)
	
	if playmsg <= 25 then
	choice = math.random(1,4)
	playshit(NPC, choice)
	else
	end
	
end

function playshit(NPC, choice, Spawn)

	if choice == 1 then
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_propaganda_1_a_c81e36af.mp3", "Good people of Qeynos, we gather today in honor of our city.  We citizens have great reason to be proud, for Qeynos has proven its worth through times of struggle and adversity.  It has risen from the chaos and darkness of the Age of Cataclysms to become first among all the cities of Norrath.  Qeynos- city of valor and defender of the meek.  These are not empty words; even those far beyond our borders speak of our accomplishments! Everyone, look around you.  The beautiful towers and spires, the gardens, buildings and bustling market places- we live in a paradise without equal.  It is hard to believe there was once a time when Qeynos lay in ruins, its streets mired.  But our city has returned to life with even greater splendor.", "", 724319904, 1189766476, Spawn)
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_propaganda_1_b_e5f9dee6.mp3", "Who performed this miracle?  We did.  All of us, by our own hands, guided by our vision and the blessings of the gods.  Qeynos stands as proof in the power of justice, equality, and compassion.  For, as our founding patriarch, Antonius Bayle, would say: If a city will be great, it must first be good!  And our city indeed owes its greatness to the goodness and benevolent ideals we citizens uphold.", "", 1818828034, 1870559483, Spawn)
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_propaganda_1_c_1aa755c8.mp3", "In this Age of Destiny, Qeynos blossoms with abundance in both arts and commerce.  Our children are nourished in body, mind, and spirit.  Scholars, merchants, artisans, soldiers- all of us are welcome here; all of us find ample means and opportunity to share our unique gifts.  Our city is a lamp in the darkness, and a clarion call to awaken Norrath from its long nightmare of discord.  Let us remember that people in other lands look to us for hope and guidance.  We are Norrath's shining example of what civilization really and truly means.   But we mustn't fall into complacency and self-satisfaction.  There is yet much to be done.  There are refugees beyond our gates who do not enjoy the freedoms and rights we take for granted.  They scratch out their meager lives in hunger and ignorance.  Some flee persecution and violence; others are tormented by the merciless ravages of want.  We Qeynosians who live in abundance are called to reach out to these refugees, to open our hearts and hands.", "", 3038020523, 1696768651, Spawn)
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_propaganda_1_d_54e171d.mp3", "Yes, I am proud to call myself a Qeynosian.  And I am certain that every one of us here is just as proud, just as grateful, and just as eager to share the light of civilization until it shines in every corner of Norrath.   We must be extra vigilant to protect our way of life from the corruption of Freeport, which threatens us night and day.  In Freeport, they mock the ideals we hold dear.  They would make slaves of each and every one of us if they could.  We have all seen examples of their ruthlessness and cruelty, of their total disregard for righteousness, of their deceptive and treacherous ways.  We know of their unabated greed, and their appetite for territory.  How they snap up lands and goods with no thought for the rights of needs of their victims.", "", 2019122145, 3355586847, Spawn)
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_propaganda_1_e_8dd02ef3.mp3", "But Freeport shall not prevail!  We Qeynosians know that the destiny of Norrath is like the sun at dawn, like a great light which begins with a spark and illuminates the land.  Qeynos is that spark!  Qeynos will spread its light of civilization until nothing and no one remains in darkness!  And we are the ones called to carry this light.  And so ... everyone ... I beseech thee all to remember that this is indeed the Age Of Destiny.  And we Qeynosians are its children, and its acolytes ... and its greatest hope!", "", 4080984009, 3907237860, Spawn)
	
	elseif choice == 2 then
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_speech_newdawn_a_c02fffe6.mp3", "Good people of Qeynos, I declare this to be a day of festivities. Welcome everyone to our New Dawn Day celebration! The old year has passed; we stand at the threshold of a new year, full of promise and opportunity. May this be a time to reflect upon our past while looking ahead to a glorious future! One may ask, 'Why do we call the start of the new year 'New Dawn Day'?'  I believe it is because Qeynos is like the sun in  early morning. We already shine with an unmatched brilliance, but our full power has yet to come forth into the world. We have only seen a sliver of our city's golden destiny!", "", 3189486571, 2780192347, Spawn)
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_speech_newdawn_b_694279fc.mp3", "And we are all a part of that light, that shining beacon that illuminates Norrath and awakens her from her dark slumber.  As Norrath gently turns on her axis and revolves around the sun, each of us becomes a living light that guides all peoples into the Age of Destiny.  We are like the stars in the night sky.     For Qeynos must lead the way.  The ideals which we have championed are the one true hope for peace and prosperity in this world.  It is up to Qeynos to show all of Norrath what is possible when truth and justice, equality and mercy are enthroned.  I am merely a handmaid to the real rulers: our ideals.  These are what we look to for guidance.", "", 982014123, 829335521, Spawn)
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_speech_newdawn_c_4465cb71.mp3", "And words cannot express the gratitude I feel ... to be entrusted with this august responsibility.  To stand here before you and before all of Qeynos fills me with great pride.  I know that we will seize every opportunity, this new year, to advance our cause and spread liberty throughout the land! We shall not dwell on failures of times past.  Instead we will live for the future.  Each of us will strive for the common good, and for the highest ambitions to which we can aspire!  This is the meaning of New Dawn Day!", "", 3866349527, 2161431192, Spawn)
	
	elseif choice == 3 then
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_denouncement_freeport_3_a_92172058.mp3", "Fellow Qeynosians, gather around and listen closely.  If my voice sounds strained, it is because of the grave and morbid subject of which I speak.  I had prayed that such disturbing words need never be spoken in Qeynos.  But these are times of great danger, and you must be warned. Our enemy, Lucan D'Lere, the tyrant of Freeport, is no ordinary, mortal foe.  He is no mere renegade General who has allowed his personal ambition to usurp his proper loyalties.  What I am about to say will horrify you.", "", 3011381199, 3373600464, Spawn)
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_denouncement_freeport_3_b_f1948507.mp3", "As you know, Lucan has misled his subjects to see him as their savior.  No ... their god.  He has enthroned himself in the gods' place.  He has corrupted the history of Freeport, claiming every victory as his own.  His subjects praise him for the rising and setting of the sun.  They think he alone holds back the remains of the moon!  The truth, however, is too horrible to behold.  Lucan ... Lucan D'Lere ... does not even belong among the living.  His mortal life was forfeit hundreds of years ago.  The monster we see is a corpse, a skeleton with a few shreds of flesh that long for the grave-unnaturally sustained by dark magic.  ", "", 2587904628, 1366269418, Spawn)
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_denouncement_freeport_3_c_6283e942.mp3", "This is why Lucan hides in that floating sarcophagus called the Twilight Citadel.  His battle armor is really a burial shroud.  Any humanity he once possessed has long since passed over into the land of shades.   So be on your guard, but take heart.  We Qeynosians have more courage than the beaten and terrified subjects of Freeport.  We are not afraid of the dead, and will never cower before a sack of bones.  Life will triumph in Qeynos, and the burial grounds of Norrath will one day claim their own.", "", 1432372035, 3833716814, Spawn)
	
	elseif choice == 4 then
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_generic_82b8bc23.mp3", "No challenge is too great for the brave and dedicated.", "", 1245844757, 2085854167, Spawn)
	
	else
	Say(NPC,"This shouldn't have happened ERROR DEVN00B",1)
	end

end

function LeaveRange(NPC, Spawn)
end

function hailed(NPC, Spawn)
	FaceTarget(NPC, Spawn)

	local choice = math.random(1,3)

	if choice == 1 then
		PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_propaganda_1_b_e5f9dee6.mp3", "Who performed this miracle?  We did.  All of us, by our own hands, guided by our vision and the blessings of the gods.  Qeynos stands as proof in the power of justice, equality, and compassion.  For, as our founding patriarch, Antonius Bayle, would say: If a city will be great, it must first be good!  And our city indeed owes its greatness to the goodness and benevolent ideals we citizens uphold.", "", 1818828034, 1870559483, Spawn)
		PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_propaganda_1_c_1aa755c8.mp3", "In this Age of Destiny, Qeynos blossoms with abundance in both arts and commerce.  Our children are nourished in body, mind, and spirit.  Scholars, merchants, artisans, soldiers- all of us are welcome here; all of us find ample means and opportunity to share our unique gifts.  Our city is a lamp in the darkness, and a clarion call to awaken Norrath from its long nightmare of discord.  Let us remember that people in other lands look to us for hope and guidance.  We are Norrath's shining example of what civilization really and truly means.   But we mustn't fall into complacency and self-satisfaction.  There is yet much to be done.  There are refugees beyond our gates who do not enjoy the freedoms and rights we take for granted.  They scratch out their meager lives in hunger and ignorance.  Some flee persecution and violence; others are tormented by the merciless ravages of want.  We Qeynosians who live in abundance are called to reach out to these refugees, to open our hearts and hands.", "", 3038020523, 1696768651, Spawn)
		PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_propaganda_1_d_54e171d.mp3", "Yes, I am proud to call myself a Qeynosian.  And I am certain that every one of us here is just as proud, just as grateful, and just as eager to share the light of civilization until it shines in every corner of Norrath.   We must be extra vigilant to protect our way of life from the corruption of Freeport, which threatens us night and day.  In Freeport, they mock the ideals we hold dear.  They would make slaves of each and every one of us if they could.  We have all seen examples of their ruthlessness and cruelty, of their total disregard for righteousness, of their deceptive and treacherous ways.  We know of their unabated greed, and their appetite for territory.  How they snap up lands and goods with no thought for the rights of needs of their victims.", "", 2019122145, 3355586847, Spawn)
		PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_propaganda_1_e_8dd02ef3.mp3", "But Freeport shall not prevail!  We Qeynosians know that the destiny of Norrath is like the sun at dawn, like a great light which begins with a spark and illuminates the land.  Qeynos is that spark!  Qeynos will spread its light of civilization until nothing and no one remains in darkness!  And we are the ones called to carry this light.  And so ... everyone ... I beseech thee all to remember that this is indeed the Age Of Destiny.  And we Qeynosians are its children, and its acolytes ... and its greatest hope!", "", 4080984009, 3907237860, Spawn)
	
	elseif choice == 2 then
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_speech_newdawn_a_c02fffe6.mp3", "Good people of Qeynos, I declare this to be a day of festivities. Welcome everyone to our New Dawn Day celebration! The old year has passed; we stand at the threshold of a new year, full of promise and opportunity. May this be a time to reflect upon our past while looking ahead to a glorious future! One may ask, 'Why do we call the start of the new year 'New Dawn Day'?'  I believe it is because Qeynos is like the sun in  early morning. We already shine with an unmatched brilliance, but our full power has yet to come forth into the world. We have only seen a sliver of our city's golden destiny!", "", 3189486571, 2780192347, Spawn)
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_speech_newdawn_b_694279fc.mp3", "And we are all a part of that light, that shining beacon that illuminates Norrath and awakens her from her dark slumber.  As Norrath gently turns on her axis and revolves around the sun, each of us becomes a living light that guides all peoples into the Age of Destiny.  We are like the stars in the night sky.     For Qeynos must lead the way.  The ideals which we have championed are the one true hope for peace and prosperity in this world.  It is up to Qeynos to show all of Norrath what is possible when truth and justice, equality and mercy are enthroned.  I am merely a handmaid to the real rulers: our ideals.  These are what we look to for guidance.", "", 982014123, 829335521, Spawn)
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_speech_newdawn_c_4465cb71.mp3", "And words cannot express the gratitude I feel ... to be entrusted with this august responsibility.  To stand here before you and before all of Qeynos fills me with great pride.  I know that we will seize every opportunity, this new year, to advance our cause and spread liberty throughout the land! We shall not dwell on failures of times past.  Instead we will live for the future.  Each of us will strive for the common good, and for the highest ambitions to which we can aspire!  This is the meaning of New Dawn Day!", "", 3866349527, 2161431192, Spawn)
	PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_generic_82b8bc23.mp3", "No challenge is too great for the brave and dedicated.", "", 1245844757, 2085854167, Spawn)
	
	elseif choice == 3 then
		PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_propaganda_1_a_c81e36af.mp3", "Good people of Qeynos, we gather today in honor of our city.  We citizens have great reason to be proud, for Qeynos has proven its worth through times of struggle and adversity.  It has risen from the chaos and darkness of the Age of Cataclysms to become first among all the cities of Norrath.  Qeynos- city of valor and defender of the meek.  These are not empty words; even those far beyond our borders speak of our accomplishments! Everyone, look around you.  The beautiful towers and spires, the gardens, buildings and bustling market places- we live in a paradise without equal.  It is hard to believe there was once a time when Qeynos lay in ruins, its streets mired.  But our city has returned to life with even greater splendor.", "", 724319904, 1189766476, Spawn)
		PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_denouncement_freeport_3_a_92172058.mp3", "Fellow Qeynosians, gather around and listen closely.  If my voice sounds strained, it is because of the grave and morbid subject of which I speak.  I had prayed that such disturbing words need never be spoken in Qeynos.  But these are times of great danger, and you must be warned. Our enemy, Lucan D'Lere, the tyrant of Freeport, is no ordinary, mortal foe.  He is no mere renegade General who has allowed his personal ambition to usurp his proper loyalties.  What I am about to say will horrify you.", "", 3011381199, 3373600464, Spawn)
		PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_denouncement_freeport_3_b_f1948507.mp3", "As you know, Lucan has misled his subjects to see him as their savior.  No ... their god.  He has enthroned himself in the gods' place.  He has corrupted the history of Freeport, claiming every victory as his own.  His subjects praise him for the rising and setting of the sun.  They think he alone holds back the remains of the moon!  The truth, however, is too horrible to behold.  Lucan ... Lucan D'Lere ... does not even belong among the living.  His mortal life was forfeit hundreds of years ago.  The monster we see is a corpse, a skeleton with a few shreds of flesh that long for the grave-unnaturally sustained by dark magic.  ", "", 2587904628, 1366269418, Spawn)
		PlayFlavor(NPC, "voiceover/english/queen_antonia_bayle/qey_north/eco_200_statue_queen_antonia_bayle_denouncement_freeport_3_c_6283e942.mp3", "This is why Lucan hides in that floating sarcophagus called the Twilight Citadel.  His battle armor is really a burial shroud.  Any humanity he once possessed has long since passed over into the land of shades.   So be on your guard, but take heart.  We Qeynosians have more courage than the beaten and terrified subjects of Freeport.  We are not afraid of the dead, and will never cower before a sack of bones.  Life will triumph in Qeynos, and the burial grounds of Norrath will one day claim their own.", "", 1432372035, 3833716814, Spawn)
	else
	end

end

